/*
  This file was generated automatically with scripts/maple2c.py.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2025 (X86 64 LINUX)
  Maple source      : maple/if_mgga/mgga_xc_ml26.mpl
  Type of functional: if_mgga
*/

#define ifxc_maple2c_order 0
#define IFXC_MAPLE2C_FLAGS (IFXC_MGGA_FLAGS_HAVE_EXC)


#ifndef XC_DONT_COMPILE_EXC
GPU_DEVICE_FUNCTION static inline void
func_exc_unpol(const xc_func_type *p, size_t ip, const double *rho, const double *sigma, const double *lapl, const double *tau, xc_mgga_out_params *out)
{ 
  double t3, t4, t5, t7, t8, t9, t11, t12;
  double t14, t15, t16, t18, t19, t20, t21, t22;
  double t23, t27, t28, t30, t31, t35, t37, t38;
  double t39, t42, t44, t45, t46, t47, t49, t51;
  double t52, t53, t54, t55, t60, t64, t66, t67;
  double t70, t72, t73, t78, t80, t84, t85, t86;
  double t87, t89, t90, t91, t95, t104, t110, t114;
  double t126, t127, t145, t155, t160, t162, t163, t167;
  double t172, t175, t177, t179, t182, t183, t184, t185;
  double t187, t191, t192, t197, t200, t202, t203, t208;
  double t211, t213, t214, t221, tzk0, t222, t224, t225;
  double t226, t228, t231, t232, t234, t237, t238, t241;
  double t245, t247, t248, t251, t252, t254, t257, t261;
  double t267, t268, t270, t271, t272, t273, t274, t276;
  double t279, t284, t289, t294, t297, t301, t307, t309;
  double t321, t324, t325, t327, t329, t332, t334, t336;
  double t338, t341, t343, t344, t345, t349, t350, t354;
  double t355, t365, t368, t371, t375, t377, t378, t382;
  double t383, t387, t397, t400, t403, t404, t407, t408;
  double t410, t411, t412, t415, t420, t421, t422, t423;
  double t424, t425, t430, t431, t434, t436, t440, t443;
  double t444, t445, t446, t448, t449, t454, t456, t460;
  double t465, t472, t474, t476, t480, t482, t483, t486;
  double t488, t489, t499, t501, t505, t507, t508, t511;
  double t514, t517, t519, t520, tzk1, t525, tzk2, t528;
  double t529, t532, tzk3, t539, t541, tzk4, tzk5, t554;
  double tzk6, t560, tzk7, t572, tzk8, t573, t575, t576;
  double t578, t579, t583, tzk9, t584, t586, t587, t591;
  double tzk10, t592, t594, t595, t599, tzk11, t600, t602;
  double t603, t607, tzk12, t608, t611, t615, tzk13, t616;
  double t617, t619, t620, t624, tzk14, t625, t626, t627;
  double t628, t632, tzk15, t633, t637, tzk16, t638, t642;
  double tzk17, t643, t647, tzk18, t648, t649, t650, t654;
  double tzk19, t656, t657, t661, tzk20, t665, tzk21, t669;
  double tzk22, t672, t673, t676, t680, tzk23, t681, t682;
  double t686, tzk24, t690, tzk25, t693, t696, t697, t701;
  double tzk26, t702, t706, tzk27, t710, tzk28, t714, tzk29;
  double t718, tzk30, t723, tzk31, t725, t729, tzk32, t731;
  double t735, tzk33, t741, tzk34, t746, tzk35, t750, tzk36;
  double t754, tzk37, t755, t756, t760, tzk38, t761, t765;
  double tzk39, t769, tzk40, t773, tzk41, t778, tzk42, t784;
  double tzk43, t790, tzk44, t792, t796, tzk45, t797, t801;
  double tzk46, t805, tzk47, tzk48, tzk49, tzk50, tzk51, tzk52;
  double t806, tzk53, t810, tzk54, t814, tzk55, t815, t816;
  double t818, tzk56, t827, t830, t839, t848, tzk57, t852;
  double tzk58, tzk59, tzk60, tzk61, tzk62, tzk63, tzk64, tzk65;
  double t860, t865, tzk66, t873, tzk67, t880, tzk68;

  t3 = rho[0] / 0.2e1 <= p->dens_threshold;
  t4 = M_CBRT3;
  t5 = M_CBRTPI;
  t7 = t4 / t5;
  t8 = 0.1e1 <= p->zeta_threshold;
  t9 = p->zeta_threshold - 0.1e1;
  t11 = my_piecewise5(t8, t9, t8, -t9, 0);
  t12 = 0.1e1 + t11;
  t14 = POW_1_3(p->zeta_threshold);
  t15 = t14 * p->zeta_threshold;
  t16 = POW_1_3(t12);
  t18 = my_piecewise3(t12 <= p->zeta_threshold, t15, t16 * t12);
  t19 = POW_1_3(rho[0]);
  t20 = t18 * t19;
  t21 = sqrt(0.3e1);
  t22 = sqrt(sigma[0]);
  t23 = M_CBRT2;
  t27 = M_CBRT6;
  t28 = t27 * t27;
  t30 = M_PI * M_PI;
  t31 = POW_1_3(t30);
  t35 = sqrt(t22 * t23 / t19 / rho[0] * t28 / t31);
  t37 = 0.33684323989301858702e-1 * t21 * t35;
  t38 = log(DBL_EPSILON);
  t39 = 0.1e1 / t38;
  t42 = my_piecewise3(t37 < -t39, -t39, t37);
  t44 = exp(-0.1e1 / t42);
  t45 = my_piecewise3(t37 <= -t39, 0, t44);
  t46 = 0.1174e1 * t45;
  t47 = t23 * t23;
  t49 = t19 * t19;
  t51 = 0.1e1 / t49 / rho[0];
  t52 = tau[0] * t47 * t51;
  t53 = t31 * t31;
  t54 = 0.1e1 / t53;
  t55 = t27 * t54;
  t60 = sigma[0] / rho[0] / tau[0] / 0.8e1;
  t64 = my_piecewise3(0.e0 < 0.9999999999e0 - t60, 0.1e1 - t60, 0.1e-9);
  t66 = t52 * t55 * t64;
  t67 = 0.5e1 / 0.9e1 * t66;
  t70 = tau[0] * tau[0];
  t72 = rho[0] * rho[0];
  t73 = rho[0] * t72;
  t78 = 0.1e1 / t31 / t30;
  t80 = t64 * t64;
  t84 = tau[0] * t70;
  t85 = t72 * t72;
  t86 = rho[0] * t85;
  t87 = 0.1e1 / t86;
  t89 = t30 * t30;
  t90 = 0.1e1 / t89;
  t91 = t64 * t80;
  t95 = t70 * t70;
  t104 = t80 * t80;
  t110 = t85 * t85;
  t114 = t30 * t89;
  t126 = t89 * t89;
  t127 = 0.1e1 / t126;
  t145 = t95 * t95;
  t155 = t104 * t104;
  t160 = 0.1e1 / M_PI;
  t162 = my_piecewise3(DBL_EPSILON < t67, t67, DBL_EPSILON);
  t163 = t162 - 0.1e1;
  t167 = t163 * t163;
  t172 = atan(M_PI * (-0.12063067191025636561e1 * t163 / t162 - 0.11103356059345265253e1 * t167) / 0.2e1);
  t175 = my_piecewise3(t67 <= DBL_EPSILON, 0.99999999999999999996e0 - 0.18665085944258768548e0 * t66 - 0.3982802071644629979e0 * t70 * t23 / t19 / t73 * t28 * t78 * t80 - 0.24255988786338671402e1 * t84 * t87 * t90 * t91 - 0.30550082955089596463e0 * t95 * t47 / t49 / t72 / t85 * t27 / t53 / t89 * t104 + 0.11675206820539006889e1 * tau[0] * t95 * t23 / t19 / t110 * t28 / t31 / t114 * t64 * t104 + 0.13980660423962914871e2 * t70 * t95 / t72 / t110 * t127 * t80 * t104 + 0.65062566833713102403e1 * t84 * t95 * t47 / t49 / t73 / t110 * t27 / t53 / t126 * t91 * t104 - 0.14122917874011873194e-1 * t145 * t23 / t19 / t86 / t110 * t28 / t31 / t30 / t126 * t155, 0.2e1 * t160 * t172);
  t177 = sigma[0] * t47;
  t179 = 0.1e1 / t49 / t72;
  t182 = t177 * t179 * t27 * t54;
  t183 = 0.13342809400364015279e-2 * t182;
  t184 = sigma[0] * sigma[0];
  t185 = t184 * t23;
  t187 = 0.1e1 / t19 / t86;
  t191 = 0.30797417856580405118e-3 * t185 * t187 * t28 * t78;
  t192 = t177 * t179;
  t197 = 0.34435261707988980717e-1 * t192 * t55 * (0.1e1 + t182 / 0.24e2);
  t200 = my_piecewise3(t197 < -t39, -t39, t197);
  t202 = exp(-0.1e1 / t200);
  t203 = my_piecewise3(t197 <= -t39, 0, t202);
  t208 = t182 / 0.6e3;
  t211 = my_piecewise3(t208 < -t39, -t39, t208);
  t213 = exp(-0.1e1 / t211);
  t214 = my_piecewise3(t208 <= -t39, 0, t213);
  t221 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t20 * (0.1174e1 - t46 + (0.1e1 - t175) * (-0.174e0 - t183 - t191 + t46 + t203 * (0.1e0 + t183 + t191 - t46)) * (0.1e1 - t214)));
  tzk0 = 0.2e1 * t221;

  t222 = POW_1_3(t160);
  t224 = M_CBRT4;
  t225 = t224 * t224;
  t226 = 0.1e1 / t19;
  t228 = t4 * t222 * t225 * t226;
  t231 = 0.1e1 / (0.1e1 + 0.5140025e-1 * t228);
  t232 = 0.468e-1 * t231;
  t234 = exp(0.1e1 * t231);
  t237 = sigma[0] * t179;
  t238 = t4 * t54 * t237;
  t241 = POW_1_4(0.1e1 + 0.51781333333333333332e0 * t238);
  t245 = 0.1e1 + (t234 - 0.1e1) * (0.1e1 - 0.1e1 / t241);
  t247 = my_piecewise3(t245 < DBL_MIN, DBL_MIN, t245);
  t248 = log(t247);
  t251 = t23 - 0.1e1;
  t252 = my_piecewise3(t8, t15, 1);
  t254 = 0.2e1 * t252 - 0.2e1;
  t257 = 0.1e1 / t251 / 0.2e1;
  t261 = (-t232 + 0.468e-1 * t248) * (0.1e1 - 0.23631e1 * t251 * t254 * t257);
  t267 = (tau[0] * t51 - t237 / 0.8e1) * t27 * t54 * t47;
  t268 = 0.5e1 / 0.9e1 * t267;
  t270 = 0.1e1 / DBL_EPSILON;
  t271 = t4 * t4;
  t272 = t222 * t222;
  t273 = t271 * t272;
  t274 = t273 * t225;
  t276 = pow(t228, 0.65e0);
  t279 = pow(t228, 0.9e0);
  t284 = pow(t228, 0.12e1);
  t289 = t4 * t31 * (0.1e1 + 0.4061261981781177613e-1 * t276) / (0.1e1 + 0.1866634826870181886e-1 * t279) / (0.1e1 + 0.56839371244139928087e-2 * t284);
  t294 = sqrt(t228);
  t297 = POW_3_2(t228);
  t301 = t273 * t224 / t49;
  t307 = log(0.1e1 + 0.16081979498692535067e2 / (0.379785e1 * t294 + 0.8969e0 * t228 + 0.204775e0 * t297 + 0.123235e0 * t301));
  t309 = 0.621814e-1 * (0.1e1 + 0.53425e-1 * t228) * t307;
  t321 = log(0.1e1 + 0.29608749977793437516e2 / (0.51785e1 * t294 + 0.905775e0 * t228 + 0.1100325e0 * t297 + 0.1241775e0 * t301));
  t324 = 0.19751673498613801407e-1 * t254 * t257 * (0.1e1 + 0.278125e-1 * t228) * t321;
  t325 = -t309 + t324 + t232;
  t327 = my_piecewise3(-DBL_EPSILON < t325, -DBL_EPSILON, t325);
  t329 = (-0.36576794167600310304e-1 * t289 + 0.20989736912384607617e0) / t327;
  t332 = 0.5e1 / 0.36e2 * t228 * t267;
  t334 = my_piecewise3(DBL_EPSILON < t332, t332, DBL_EPSILON);
  t336 = (t268 - 0.1e1) / t334;
  t338 = my_piecewise3(0.e0 <= t336, t336, -t336);
  t341 = 0.3e1 / 0.16e2 * t274 * t329 * t338;
  t343 = 0.1e1 / t30;
  t344 = t270 < t341;
  t345 = my_piecewise3(t344, t341, t270);
  t349 = t345 * t345;
  t350 = t345 * t349;
  t354 = 0.1e1 / t114;
  t355 = t349 * t349;
  t365 = my_piecewise3(t344, t270, t341);
  t368 = atan(M_PI * t365 / 0.2e1);
  t371 = my_piecewise3(t270 <= t341, 0.1e1 - 0.4e1 * t343 / t345 + 0.16e2 / 0.3e1 * t90 / t350 - 0.64e2 / 0.5e1 * t354 / t345 / t355 + 0.256e3 / 0.7e1 * t127 / t350 / t355, 0.2e1 * t160 * t368);
  t375 = 0.3e1 / 0.16e2 * t274 * t329 * t336;
  t377 = t270 < t375;
  t378 = my_piecewise3(t377, t375, t270);
  t382 = t378 * t378;
  t383 = t378 * t382;
  t387 = t382 * t382;
  t397 = my_piecewise3(t377, t270, t375);
  t400 = atan(M_PI * t397 / 0.2e1);
  t403 = my_piecewise3(t270 <= t375, 0.1e1 - 0.4e1 * t343 / t378 + 0.16e2 / 0.3e1 * t90 / t383 - 0.64e2 / 0.5e1 * t354 / t378 / t387 + 0.256e3 / 0.7e1 * t127 / t383 / t387, 0.2e1 * t160 * t400);
  t404 = my_piecewise3(t268 < 0.e0, 0.2e1 + t371, t403);
  t407 = POW_1_3(0.16e2);
  t408 = t407 * t407;
  t410 = t14 * t14;
  t411 = my_piecewise3(t8, t410, 1);
  t412 = t411 * t411;
  t415 = -0.70121174589195667679e-1 * t289 + 0.32022742560873636667e-1;
  t420 = log(0.2e1);
  t421 = 0.1e1 - t420;
  t422 = t421 * t343;
  t423 = t411 * t412;
  t424 = -t309 + t324;
  t425 = 0.1e1 / t421;
  t430 = exp(-t424 * t425 * t30 / t423);
  t431 = t430 - 0.1e1;
  t434 = t54 * t415 * t425;
  t436 = 0.1e1 / t431;
  t440 = 0.1e1 / t19 / t72;
  t443 = t30 * t436 * sigma[0] * t440 * t23 * t271;
  t444 = t222 * t408 * t434 * t443;
  t445 = t444 / 0.32e2;
  t446 = 0.1e1 - t445;
  t448 = my_piecewise3(DBL_EPSILON < t446, t446, DBL_EPSILON);
  t449 = POW_1_4(t448);
  t454 = t415 * t415;
  t456 = t421 * t421;
  t460 = t431 * t431;
  t465 = 0.1e1 / t49 / t85;
  t472 = 0.1e1 / (0.1e1 + 0.3e1 / 0.1024e4 * t272 * t407 * t78 * t454 / t456 * t89 / t460 * t184 * t465 * t47 * t4);
  t474 = 0.1e1 - 0.5e1 / 0.64e2 * t444;
  t476 = my_piecewise3(DBL_EPSILON < t474, t474, DBL_EPSILON);
  t480 = 0.1e1 + t431 * (0.1e1 - 0.1e1 / t449) * (0.1e1 - t472 + 0.1e1 / t476);
  t482 = my_piecewise3(DBL_MIN < t480, t480, DBL_MIN);
  t483 = log(t482);
  t486 = 0.1e1 + t445;
  t488 = my_piecewise3(DBL_EPSILON < t486, t486, DBL_EPSILON);
  t489 = POW_1_4(t488);
  t499 = 0.1e1 + (t430 + 0.185e1) * t222 * t408 * t434 * t443 / 0.128e3;
  t501 = my_piecewise3(DBL_EPSILON < t499, t499, DBL_EPSILON);
  t505 = 0.1e1 + t431 * (0.1e1 - 0.1e1 / t489) * (0.1e1 - t472 - 0.1e1 / t501);
  t507 = my_piecewise3(DBL_MIN < t505, t505, DBL_MIN);
  t508 = log(t507);
  t511 = my_piecewise3(0.e0 <= -0.3e1 / 0.16e2 * t272 * t225 * t408 * t54 * t412 * t415, t422 * t423 * t483, t422 * t423 * t508);
  t514 = t238 / 0.3e3;
  t517 = my_piecewise3(t514 < -t39, -t39, t514);
  t519 = exp(-0.1e1 / t517);
  t520 = my_piecewise3(t514 <= -t39, 0, t519);
  tzk1 = t261 + (0.1e1 - t404) * (-t309 + t324 + t511 - t261) * (0.1e1 - t520);

  t525 = 0.1e1 / (0.1e1 + 0.349e0 * t226);
  tzk2 = -0.4918e-1 * t525;

  t528 = exp(-0.2533e0 * t226);
  t529 = t528 * t525;
  t532 = (0.2533e0 + 0.349e0 * t525) * t226;
  tzk3 = -0.649176e-2 * t529 * t237 * (-0.1e1 / 0.72e2 - 0.7e1 / 0.72e2 * t532);

  t539 = p->zeta_threshold * p->zeta_threshold;
  t541 = my_piecewise3(t8, t410 * t539, 1);
  tzk4 = -0.1947528e-2 * t529 * t271 * t53 * t541;

  tzk5 = 0.81147e-3 * t529 * (0.5e1 / 0.2e1 - t532 / 0.18e2) * t237 * t541;

  t554 = my_piecewise3(t8, t410 * p->zeta_threshold * t539, 1);
  tzk6 = 0.45081666666666666667e-4 * t529 * (t532 - 0.11e2) * t237 * t554;

  t560 = my_piecewise3(t8, t539, 1);
  tzk7 = -0.81147e-3 * t529 * t23 * (0.4e1 / 0.3e1 * t177 * t179 * t541 - t560 * sigma[0] * t47 * t179 * t541 / 0.2e1);

  t572 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t20);
  tzk8 = 0.2e1 * t572;

  t573 = t7 * t18;
  t575 = 0.3e1 / 0.1e2 * t28 * t53;
  t576 = t575 - t52;
  t578 = t575 + t52;
  t579 = 0.1e1 / t578;
  t583 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t19 * t576 * t579);
  tzk9 = 0.2e1 * t583;

  t584 = t576 * t576;
  t586 = t578 * t578;
  t587 = 0.1e1 / t586;
  t591 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t19 * t584 * t587);
  tzk10 = 0.2e1 * t591;

  t592 = t576 * t584;
  t594 = t578 * t586;
  t595 = 0.1e1 / t594;
  t599 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t19 * t592 * t595);
  tzk11 = 0.2e1 * t599;

  t600 = t584 * t584;
  t602 = t586 * t586;
  t603 = 0.1e1 / t602;
  t607 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t19 * t600 * t603);
  tzk12 = 0.2e1 * t607;

  t608 = t576 * t600;
  t611 = 0.1e1 / t578 / t602;
  t615 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t19 * t608 * t611);
  tzk13 = 0.2e1 * t615;

  t616 = t4 * t18;
  t617 = t616 * t440;
  t619 = 0.1e1 + 0.4e-2 * t192;
  t620 = 0.1e1 / t619;
  t624 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t617 * t177 * t620);
  tzk14 = 0.2e1 * t624;

  t625 = t440 * sigma[0];
  t626 = t616 * t625;
  t627 = t47 * t620;
  t628 = t576 * t579;
  t632 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t628);
  tzk15 = 0.2e1 * t632;

  t633 = t584 * t587;
  t637 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t633);
  tzk16 = 0.2e1 * t637;

  t638 = t592 * t595;
  t642 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t638);
  tzk17 = 0.2e1 * t642;

  t643 = t600 * t603;
  t647 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t643);
  tzk18 = 0.2e1 * t647;

  t648 = t616 * t87;
  t649 = t619 * t619;
  t650 = 0.1e1 / t649;
  t654 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t648 * t185 * t650);
  tzk19 = 0.2e1 * t654;

  t656 = t616 * t87 * t184;
  t657 = t23 * t650;
  t661 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t656 * t657 * t628);
  tzk20 = 0.2e1 * t661;

  t665 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t656 * t657 * t633);
  tzk21 = 0.2e1 * t665;

  t669 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t656 * t657 * t638);
  tzk22 = 0.2e1 * t669;

  t672 = 0.1e1 / t49 / t73 / t85;
  t673 = sigma[0] * t184;
  t676 = 0.1e1 / t619 / t649;
  t680 = my_piecewise3(t3, 0, -0.6554727007250838542e-7 * t616 * t672 * t673 * t676);
  tzk23 = 0.2e1 * t680;

  t681 = t616 * t672;
  t682 = t673 * t676;
  t686 = my_piecewise3(t3, 0, -0.6554727007250838542e-7 * t681 * t682 * t628);
  tzk24 = 0.2e1 * t686;

  t690 = my_piecewise3(t3, 0, -0.6554727007250838542e-7 * t681 * t682 * t633);
  tzk25 = 0.2e1 * t690;

  t693 = POW_1_3(0.1e1 / t12);
  t696 = 0.1e1 + 0.39999999999999999998e0 * t226 * t23 * t693;
  t697 = 0.1e1 / t696;
  t701 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t20 * t697);
  tzk26 = 0.2e1 * t701;

  t702 = t19 * t697;
  t706 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t702 * t628);
  tzk27 = 0.2e1 * t706;

  t710 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t702 * t633);
  tzk28 = 0.2e1 * t710;

  t714 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t702 * t638);
  tzk29 = 0.2e1 * t714;

  t718 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t702 * t643);
  tzk30 = 0.2e1 * t718;

  t723 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t617 * t177 * t620 * t697);
  tzk31 = 0.2e1 * t723;

  t725 = t697 * t576 * t579;
  t729 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t725);
  tzk32 = 0.2e1 * t729;

  t731 = t697 * t584 * t587;
  t735 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t731);
  tzk33 = 0.2e1 * t735;

  t741 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t697 * t592 * t595);
  tzk34 = 0.2e1 * t741;

  t746 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t648 * t185 * t650 * t697);
  tzk35 = 0.2e1 * t746;

  t750 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t656 * t657 * t725);
  tzk36 = 0.2e1 * t750;

  t754 = my_piecewise3(t3, 0, -0.81934087590635481775e-5 * t656 * t657 * t731);
  tzk37 = 0.2e1 * t754;

  t755 = t696 * t696;
  t756 = 0.1e1 / t755;
  t760 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t20 * t756);
  tzk38 = 0.2e1 * t760;

  t761 = t19 * t756;
  t765 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t761 * t628);
  tzk39 = 0.2e1 * t765;

  t769 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t761 * t633);
  tzk40 = 0.2e1 * t769;

  t773 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t761 * t638);
  tzk41 = 0.2e1 * t773;

  t778 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t617 * t177 * t620 * t756);
  tzk42 = 0.2e1 * t778;

  t784 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t756 * t576 * t579);
  tzk43 = 0.2e1 * t784;

  t790 = my_piecewise3(t3, 0, -0.10241760948829435222e-2 * t626 * t627 * t756 * t584 * t587);
  tzk44 = 0.2e1 * t790;

  t792 = 0.1e1 / t696 / t755;
  t796 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t7 * t20 * t792);
  tzk45 = 0.2e1 * t796;

  t797 = t19 * t792;
  t801 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t797 * t628);
  tzk46 = 0.2e1 * t801;

  t805 = my_piecewise3(t3, 0, -0.3e1 / 0.8e1 * t573 * t797 * t633);
  tzk47 = 0.2e1 * t805;

  tzk48 = t424;

  tzk49 = t628 * tzk48;

  tzk50 = t633 * tzk48;

  tzk51 = t638 * tzk48;

  tzk52 = t643 * tzk48;

  t806 = t608 * t611;
  tzk53 = t806 * tzk48;

  t810 = t584 * t600 / t586 / t602;
  tzk54 = t810 * tzk48;

  t814 = t592 * t600 / t594 / t602;
  tzk55 = t814 * tzk48;

  t815 = t600 * t600;
  t816 = t602 * t602;
  t818 = t815 / t816;
  tzk56 = t818 * tzk48;

  t827 = t425 * t436;
  t830 = t412 * t412;
  t839 = t625 * t23 / t412 * t271 / t222 * t224 / 0.96e2 + 0.21437009059034868486e-3 * t827 * t184 * t465 * t47 / t830 * t4 / t272 * t225;
  t848 = log(0.1e1 + 0.65854491829355115987e0 * t839 * t425 / (0.1e1 + 0.65854491829355115987e0 * t827 * t839));
  tzk57 = t422 * t423 * t848;

  t852 = t343 * t423 * t848;
  tzk58 = t628 * t421 * t852;

  tzk59 = t633 * t421 * t852;

  tzk60 = t638 * t421 * t852;

  tzk61 = t643 * t421 * t852;

  tzk62 = t806 * t421 * t852;

  tzk63 = t810 * t421 * t852;

  tzk64 = t814 * t421 * t852;

  tzk65 = t818 * t421 * t852;

  t860 = my_piecewise3(t8, p->zeta_threshold, 1);
  t865 = 0.1e1 / (t47 * t19 / 0.2e1 + 0.349e0);
  tzk66 = -0.94485e-2 * t860 * t47 * t19 * t865;

  t873 = POW_2(0.1e1 + 0.6e-2 * t192);
  tzk67 = 0.1117728e-4 * t860 * t87 * t865 * t184 / t873;

  t880 = POW_2(0.1e1 + 0.6e-2 * t237);
  tzk68 = t525 * (-0.159068e0 + 0.286308e-6 * t184 * t187 / t880) / 0.4e1;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC)) {
    out->zk[ip*p->dim.zk + 0] += tzk0;
    out->zk[ip*p->dim.zk + 1] += tzk1;
    out->zk[ip*p->dim.zk + 2] += tzk2;
    out->zk[ip*p->dim.zk + 3] += tzk3;
    out->zk[ip*p->dim.zk + 4] += tzk4;
    out->zk[ip*p->dim.zk + 5] += tzk5;
    out->zk[ip*p->dim.zk + 6] += tzk6;
    out->zk[ip*p->dim.zk + 7] += tzk7;
    out->zk[ip*p->dim.zk + 8] += tzk8;
    out->zk[ip*p->dim.zk + 9] += tzk9;
    out->zk[ip*p->dim.zk + 10] += tzk10;
    out->zk[ip*p->dim.zk + 11] += tzk11;
    out->zk[ip*p->dim.zk + 12] += tzk12;
    out->zk[ip*p->dim.zk + 13] += tzk13;
    out->zk[ip*p->dim.zk + 14] += tzk14;
    out->zk[ip*p->dim.zk + 15] += tzk15;
    out->zk[ip*p->dim.zk + 16] += tzk16;
    out->zk[ip*p->dim.zk + 17] += tzk17;
    out->zk[ip*p->dim.zk + 18] += tzk18;
    out->zk[ip*p->dim.zk + 19] += tzk19;
    out->zk[ip*p->dim.zk + 20] += tzk20;
    out->zk[ip*p->dim.zk + 21] += tzk21;
    out->zk[ip*p->dim.zk + 22] += tzk22;
    out->zk[ip*p->dim.zk + 23] += tzk23;
    out->zk[ip*p->dim.zk + 24] += tzk24;
    out->zk[ip*p->dim.zk + 25] += tzk25;
    out->zk[ip*p->dim.zk + 26] += tzk26;
    out->zk[ip*p->dim.zk + 27] += tzk27;
    out->zk[ip*p->dim.zk + 28] += tzk28;
    out->zk[ip*p->dim.zk + 29] += tzk29;
    out->zk[ip*p->dim.zk + 30] += tzk30;
    out->zk[ip*p->dim.zk + 31] += tzk31;
    out->zk[ip*p->dim.zk + 32] += tzk32;
    out->zk[ip*p->dim.zk + 33] += tzk33;
    out->zk[ip*p->dim.zk + 34] += tzk34;
    out->zk[ip*p->dim.zk + 35] += tzk35;
    out->zk[ip*p->dim.zk + 36] += tzk36;
    out->zk[ip*p->dim.zk + 37] += tzk37;
    out->zk[ip*p->dim.zk + 38] += tzk38;
    out->zk[ip*p->dim.zk + 39] += tzk39;
    out->zk[ip*p->dim.zk + 40] += tzk40;
    out->zk[ip*p->dim.zk + 41] += tzk41;
    out->zk[ip*p->dim.zk + 42] += tzk42;
    out->zk[ip*p->dim.zk + 43] += tzk43;
    out->zk[ip*p->dim.zk + 44] += tzk44;
    out->zk[ip*p->dim.zk + 45] += tzk45;
    out->zk[ip*p->dim.zk + 46] += tzk46;
    out->zk[ip*p->dim.zk + 47] += tzk47;
    out->zk[ip*p->dim.zk + 48] += tzk48;
    out->zk[ip*p->dim.zk + 49] += tzk49;
    out->zk[ip*p->dim.zk + 50] += tzk50;
    out->zk[ip*p->dim.zk + 51] += tzk51;
    out->zk[ip*p->dim.zk + 52] += tzk52;
    out->zk[ip*p->dim.zk + 53] += tzk53;
    out->zk[ip*p->dim.zk + 54] += tzk54;
    out->zk[ip*p->dim.zk + 55] += tzk55;
    out->zk[ip*p->dim.zk + 56] += tzk56;
    out->zk[ip*p->dim.zk + 57] += tzk57;
    out->zk[ip*p->dim.zk + 58] += tzk58;
    out->zk[ip*p->dim.zk + 59] += tzk59;
    out->zk[ip*p->dim.zk + 60] += tzk60;
    out->zk[ip*p->dim.zk + 61] += tzk61;
    out->zk[ip*p->dim.zk + 62] += tzk62;
    out->zk[ip*p->dim.zk + 63] += tzk63;
    out->zk[ip*p->dim.zk + 64] += tzk64;
    out->zk[ip*p->dim.zk + 65] += tzk65;
    out->zk[ip*p->dim.zk + 66] += tzk66;
    out->zk[ip*p->dim.zk + 67] += tzk67;
    out->zk[ip*p->dim.zk + 68] += tzk68;
  }

}

#endif


#ifndef XC_DONT_COMPILE_EXC
GPU_DEVICE_FUNCTION static inline void
func_exc_pol(const xc_func_type *p, size_t ip, const double *rho, const double *sigma, const double *lapl, const double *tau, xc_mgga_out_params *out)
{ 
  double t2, t3, t4, t6, t7, t8, t11, t12;
  double t15, t16, t17, t18, t19, t20, t22, t23;
  double t24, t26, t27, t28, t29, t30, t31, t35;
  double t36, t37, t38, t40, t42, t44, t45, t46;
  double t49, t51, t52, t53, t54, t57, t58, t59;
  double t60, t65, t69, t71, t72, t75, t76, t77;
  double t82, t83, t84, t88, t89, t90, t91, t93;
  double t94, t95, t99, t106, t107, t112, t116, t119;
  double t128, t129, t141, t146, t154, t155, t160, t162;
  double t163, t167, t172, t175, t178, t179, t180, t181;
  double t182, t184, t185, t187, t192, t195, t197, t198;
  double t203, t206, t208, t209, t216, t217, t220, t221;
  double t223, t225, t226, t227, t228, t233, t235, t238;
  double t240, t241, t242, t243, t246, t251, t255, t257;
  double t258, t261, t262, t263, t267, t271, t272, t273;
  double t274, t276, t280, t285, t290, t315, t320, t326;
  double t327, t331, t336, t339, t342, t343, t344, t345;
  double t346, t348, t349, t351, t356, t359, t361, t362;
  double t367, t370, t372, t373, t380, tzk0, t381, t383;
  double t384, t385, t387, t390, t391, t393, t397, t398;
  double t399, t402, t403, t406, t410, t412, t413, t416;
  double t417, t418, t419, t420, t422, t423, t424, t425;
  double t427, t428, t431, t436, t437, t438, t440, t441;
  double t446, t447, t448, t449, t450, t451, t452, t453;
  double t454, t455, t456, t463, t464, t466, t467, t468;
  double t469, t470, t472, t475, t480, t485, t490, t493;
  double t497, t503, t505, t506, t507, t521, t522, t525;
  double t527, t529, t532, t534, t536, t538, t541, t543;
  double t544, t545, t549, t550, t554, t555, t565, t568;
  double t571, t575, t577, t578, t582, t583, t587, t597;
  double t600, t603, t604, t608, t619, t625, t627, t629;
  double t630, t632, t633, t634, t635, t637, t642, t643;
  double t644, t645, t646, t647, t648, t650, t651, t652;
  double t653, t654, t659, t660, t666, t670, t673, t675;
  double t676, t677, t678, t680, t681, t687, t688, t690;
  double t694, t697, t700, t701, t703, t704, t711, t713;
  double t715, t719, t721, t722, t725, t727, t728, t740;
  double t742, t746, t748, t749, t752, t755, t758, t760;
  double t761, tzk1, t766, t769, t770, tzk2, t773, t774;
  double t777, tzk3, t788, t789, t790, t792, t793, t795;
  double tzk4, t800, t804, t805, tzk5, t812, t815, t819;
  double tzk6, t826, t831, tzk7, t842, t845, tzk8, t846;
  double t848, t849, t851, t852, t856, t857, t858, t860;
  double t861, t865, tzk9, t866, t868, t869, t873, t874;
  double t876, t877, t881, tzk10, t882, t885, t889, t890;
  double t893, t897, tzk11, t898, t900, t901, t905, t906;
  double t908, t909, t913, tzk12, t921, t929, tzk13, t930;
  double t931, t933, t934, t938, t939, t940, t942, t943;
  double t947, tzk14, t949, t950, t951, t955, t957, t958;
  double t959, t963, tzk15, t964, t968, t969, t973, tzk16;
  double t974, t978, t979, t983, tzk17, t984, t988, t989;
  double t993, tzk18, t994, t995, t999, t1000, t1001, t1005;
  double tzk19, t1007, t1008, t1012, t1014, t1015, t1019, tzk20;
  double t1023, t1027, tzk21, t1031, t1035, tzk22, t1036, t1037;
  double t1040, t1044, t1045, t1046, t1049, t1053, tzk23, t1055;
  double t1056, t1060, t1062, t1063, t1067, tzk24, t1071, t1075;
  double tzk25, t1076, t1077, t1080, t1083, t1084, t1088, t1089;
  double t1092, t1095, t1096, t1100, tzk26, t1101, t1105, t1106;
  double t1110, tzk27, t1114, t1118, tzk28, t1122, t1126, tzk29;
  double t1130, t1134, tzk30, t1139, t1144, tzk31, t1146, t1150;
  double t1152, t1156, tzk32, t1158, t1162, t1164, t1168, tzk33;
  double t1174, t1180, tzk34, t1185, t1190, tzk35, t1194, t1198;
  double tzk36, t1202, t1206, tzk37, t1207, t1208, t1212, t1213;
  double t1214, t1218, tzk38, t1219, t1223, t1224, t1228, tzk39;
  double t1232, t1236, tzk40, t1240, t1244, tzk41, t1249, t1254;
  double tzk42, t1260, t1266, tzk43, t1272, t1278, tzk44, t1280;
  double t1284, t1286, t1290, tzk45, t1291, t1295, t1296, t1300;
  double tzk46, t1304, t1308, tzk47, tzk48, t1310, t1311, t1312;
  double t1314, tzk49, t1315, t1316, t1318, tzk50, t1319, t1320;
  double t1322, tzk51, t1323, t1324, t1326, tzk52, t1330, tzk53;
  double t1334, tzk54, t1338, tzk55, t1339, t1340, t1342, tzk56;
  double t1350, t1360, t1369, tzk57, t1373, tzk58, tzk59, tzk60;
  double tzk61, tzk62, tzk63, tzk64, tzk65, t1381, t1384, t1387;
  double t1390, tzk66, t1397, t1406, tzk67, t1417, tzk68;

  t2 = rho[0] <= p->dens_threshold;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t7 = rho[0] + rho[1];
  t8 = 0.1e1 / t7;
  t11 = 0.2e1 * rho[0] * t8 <= p->zeta_threshold;
  t12 = p->zeta_threshold - 0.1e1;
  t15 = 0.2e1 * rho[1] * t8 <= p->zeta_threshold;
  t16 = -t12;
  t17 = rho[0] - rho[1];
  t18 = t17 * t8;
  t19 = my_piecewise5(t11, t12, t15, t16, t18);
  t20 = 0.1e1 + t19;
  t22 = POW_1_3(p->zeta_threshold);
  t23 = t22 * p->zeta_threshold;
  t24 = POW_1_3(t20);
  t26 = my_piecewise3(t20 <= p->zeta_threshold, t23, t24 * t20);
  t27 = POW_1_3(t7);
  t28 = t26 * t27;
  t29 = sqrt(0.3e1);
  t30 = sqrt(sigma[0]);
  t31 = POW_1_3(rho[0]);
  t35 = M_CBRT6;
  t36 = t35 * t35;
  t37 = M_PI * M_PI;
  t38 = POW_1_3(t37);
  t40 = t36 / t38;
  t42 = sqrt(t30 / t31 / rho[0] * t40);
  t44 = 0.33684323989301858702e-1 * t29 * t42;
  t45 = log(DBL_EPSILON);
  t46 = 0.1e1 / t45;
  t49 = my_piecewise3(t44 < -t46, -t46, t44);
  t51 = exp(-0.1e1 / t49);
  t52 = my_piecewise3(t44 <= -t46, 0, t51);
  t53 = 0.1174e1 * t52;
  t54 = t31 * t31;
  t57 = tau[0] / t54 / rho[0];
  t58 = t38 * t38;
  t59 = 0.1e1 / t58;
  t60 = t35 * t59;
  t65 = sigma[0] / rho[0] / tau[0] / 0.8e1;
  t69 = my_piecewise3(0.e0 < 0.9999999999e0 - t65, 0.1e1 - t65, 0.1e-9);
  t71 = t57 * t60 * t69;
  t72 = 0.5e1 / 0.9e1 * t71;
  t75 = tau[0] * tau[0];
  t76 = rho[0] * rho[0];
  t77 = rho[0] * t76;
  t82 = 0.1e1 / t38 / t37;
  t83 = t36 * t82;
  t84 = t69 * t69;
  t88 = tau[0] * t75;
  t89 = t76 * t76;
  t90 = rho[0] * t89;
  t91 = 0.1e1 / t90;
  t93 = t37 * t37;
  t94 = 0.1e1 / t93;
  t95 = t69 * t84;
  t99 = t75 * t75;
  t106 = t35 / t58 / t93;
  t107 = t84 * t84;
  t112 = t89 * t89;
  t116 = t37 * t93;
  t119 = t36 / t38 / t116;
  t128 = t93 * t93;
  t129 = 0.1e1 / t128;
  t141 = t35 / t58 / t128;
  t146 = t99 * t99;
  t154 = t36 / t38 / t37 / t128;
  t155 = t107 * t107;
  t160 = 0.1e1 / M_PI;
  t162 = my_piecewise3(DBL_EPSILON < t72, t72, DBL_EPSILON);
  t163 = t162 - 0.1e1;
  t167 = t163 * t163;
  t172 = atan(M_PI * (-0.12063067191025636561e1 * t163 / t162 - 0.11103356059345265253e1 * t167) / 0.2e1);
  t175 = my_piecewise3(t72 <= DBL_EPSILON, 0.99999999999999999996e0 - 0.18665085944258768548e0 * t71 - 0.19914010358223149895e0 * t75 / t31 / t77 * t83 * t84 - 0.60639971965846678506e0 * t88 * t91 * t94 * t95 - 0.76375207387723991158e-1 * t99 / t54 / t76 / t89 * t106 * t107 + 0.14594008525673758611e0 * tau[0] * t99 / t31 / t112 * t119 * t69 * t107 + 0.87379127649768217944e0 * t75 * t99 / t76 / t112 * t129 * t84 * t107 + 0.40664104271070689002e0 * t88 * t99 / t54 / t77 / t112 * t141 * t95 * t107 - 0.44134118356287103732e-3 * t146 / t31 / t90 / t112 * t154 * t155, 0.2e1 * t160 * t172);
  t178 = 0.1e1 / t54 / t76;
  t179 = sigma[0] * t178;
  t180 = t179 * t60;
  t181 = 0.13342809400364015279e-2 * t180;
  t182 = sigma[0] * sigma[0];
  t184 = 0.1e1 / t31 / t90;
  t185 = t182 * t184;
  t187 = 0.15398708928290202559e-3 * t185 * t83;
  t192 = 0.34435261707988980717e-1 * t179 * t60 * (0.1e1 + t180 / 0.24e2);
  t195 = my_piecewise3(t192 < -t46, -t46, t192);
  t197 = exp(-0.1e1 / t195);
  t198 = my_piecewise3(t192 <= -t46, 0, t197);
  t203 = t180 / 0.6e3;
  t206 = my_piecewise3(t203 < -t46, -t46, t203);
  t208 = exp(-0.1e1 / t206);
  t209 = my_piecewise3(t203 <= -t46, 0, t208);
  t216 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t28 * (0.1174e1 - t53 + (0.1e1 - t175) * (-0.174e0 - t181 - t187 + t53 + t198 * (0.1e0 + t181 + t187 - t53)) * (0.1e1 - t209)));
  t217 = rho[1] <= p->dens_threshold;
  t220 = my_piecewise5(t15, t12, t11, t16, -t17 * t8);
  t221 = 0.1e1 + t220;
  t223 = POW_1_3(t221);
  t225 = my_piecewise3(t221 <= p->zeta_threshold, t23, t223 * t221);
  t226 = t225 * t27;
  t227 = sqrt(sigma[2]);
  t228 = POW_1_3(rho[1]);
  t233 = sqrt(t227 / t228 / rho[1] * t40);
  t235 = 0.33684323989301858702e-1 * t29 * t233;
  t238 = my_piecewise3(t235 < -t46, -t46, t235);
  t240 = exp(-0.1e1 / t238);
  t241 = my_piecewise3(t235 <= -t46, 0, t240);
  t242 = 0.1174e1 * t241;
  t243 = t228 * t228;
  t246 = tau[1] / t243 / rho[1];
  t251 = sigma[2] / rho[1] / tau[1] / 0.8e1;
  t255 = my_piecewise3(0.e0 < 0.9999999999e0 - t251, 0.1e1 - t251, 0.1e-9);
  t257 = t246 * t60 * t255;
  t258 = 0.5e1 / 0.9e1 * t257;
  t261 = tau[1] * tau[1];
  t262 = rho[1] * rho[1];
  t263 = rho[1] * t262;
  t267 = t255 * t255;
  t271 = tau[1] * t261;
  t272 = t262 * t262;
  t273 = rho[1] * t272;
  t274 = 0.1e1 / t273;
  t276 = t255 * t267;
  t280 = t261 * t261;
  t285 = t267 * t267;
  t290 = t272 * t272;
  t315 = t280 * t280;
  t320 = t285 * t285;
  t326 = my_piecewise3(DBL_EPSILON < t258, t258, DBL_EPSILON);
  t327 = t326 - 0.1e1;
  t331 = t327 * t327;
  t336 = atan(M_PI * (-0.12063067191025636561e1 * t327 / t326 - 0.11103356059345265253e1 * t331) / 0.2e1);
  t339 = my_piecewise3(t258 <= DBL_EPSILON, 0.99999999999999999996e0 - 0.18665085944258768548e0 * t257 - 0.19914010358223149895e0 * t261 / t228 / t263 * t83 * t267 - 0.60639971965846678506e0 * t271 * t274 * t94 * t276 - 0.76375207387723991158e-1 * t280 / t243 / t262 / t272 * t106 * t285 + 0.14594008525673758611e0 * tau[1] * t280 / t228 / t290 * t119 * t255 * t285 + 0.87379127649768217944e0 * t261 * t280 / t262 / t290 * t129 * t267 * t285 + 0.40664104271070689002e0 * t271 * t280 / t243 / t263 / t290 * t141 * t276 * t285 - 0.44134118356287103732e-3 * t315 / t228 / t273 / t290 * t154 * t320, 0.2e1 * t160 * t336);
  t342 = 0.1e1 / t243 / t262;
  t343 = sigma[2] * t342;
  t344 = t343 * t60;
  t345 = 0.13342809400364015279e-2 * t344;
  t346 = sigma[2] * sigma[2];
  t348 = 0.1e1 / t228 / t273;
  t349 = t346 * t348;
  t351 = 0.15398708928290202559e-3 * t349 * t83;
  t356 = 0.34435261707988980717e-1 * t343 * t60 * (0.1e1 + t344 / 0.24e2);
  t359 = my_piecewise3(t356 < -t46, -t46, t356);
  t361 = exp(-0.1e1 / t359);
  t362 = my_piecewise3(t356 <= -t46, 0, t361);
  t367 = t344 / 0.6e3;
  t370 = my_piecewise3(t367 < -t46, -t46, t367);
  t372 = exp(-0.1e1 / t370);
  t373 = my_piecewise3(t367 <= -t46, 0, t372);
  t380 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t6 * t226 * (0.1174e1 - t242 + (0.1e1 - t339) * (-0.174e0 - t345 - t351 + t242 + t362 * (0.1e0 + t345 + t351 - t242)) * (0.1e1 - t373)));
  tzk0 = t216 + t380;

  t381 = POW_1_3(t160);
  t383 = M_CBRT4;
  t384 = t383 * t383;
  t385 = 0.1e1 / t27;
  t387 = t3 * t381 * t384 * t385;
  t390 = 0.1e1 / (0.1e1 + 0.5140025e-1 * t387);
  t391 = 0.468e-1 * t390;
  t393 = exp(0.1e1 * t390);
  t397 = sigma[0] + 0.2e1 * sigma[1] + sigma[2];
  t398 = t7 * t7;
  t399 = t27 * t27;
  t402 = t397 / t399 / t398;
  t403 = t3 * t59 * t402;
  t406 = POW_1_4(0.1e1 + 0.51781333333333333332e0 * t403);
  t410 = 0.1e1 + (t393 - 0.1e1) * (0.1e1 - 0.1e1 / t406);
  t412 = my_piecewise3(t410 < DBL_MIN, DBL_MIN, t410);
  t413 = log(t412);
  t416 = M_CBRT2;
  t417 = t416 - 0.1e1;
  t418 = 0.1e1 + t18;
  t419 = t418 <= p->zeta_threshold;
  t420 = POW_1_3(t418);
  t422 = my_piecewise3(t419, t23, t420 * t418);
  t423 = 0.1e1 - t18;
  t424 = t423 <= p->zeta_threshold;
  t425 = POW_1_3(t423);
  t427 = my_piecewise3(t424, t23, t425 * t423);
  t428 = t422 + t427 - 0.2e1;
  t431 = 0.1e1 / t417 / 0.2e1;
  t436 = t17 * t17;
  t437 = t436 * t436;
  t438 = t437 * t437;
  t440 = t398 * t398;
  t441 = t440 * t440;
  t446 = (-t391 + 0.468e-1 * t413) * (0.1e1 - 0.23631e1 * t417 * t428 * t431) * (0.1e1 - t437 * t438 / t440 / t441);
  t447 = t418 / 0.2e1;
  t448 = POW_1_3(t447);
  t449 = t448 * t448;
  t450 = t449 * t447;
  t451 = t57 * t450;
  t452 = t423 / 0.2e1;
  t453 = POW_1_3(t452);
  t454 = t453 * t453;
  t455 = t454 * t452;
  t456 = t246 * t455;
  t463 = (t451 + t456 - t402 / 0.8e1) * t35 * t59 / (t450 + t455);
  t464 = 0.5e1 / 0.9e1 * t463;
  t466 = 0.1e1 / DBL_EPSILON;
  t467 = t3 * t3;
  t468 = t381 * t381;
  t469 = t467 * t468;
  t470 = t469 * t384;
  t472 = pow(t387, 0.65e0);
  t475 = pow(t387, 0.9e0);
  t480 = pow(t387, 0.12e1);
  t485 = t3 * t38 * (0.1e1 + 0.4061261981781177613e-1 * t472) / (0.1e1 + 0.1866634826870181886e-1 * t475) / (0.1e1 + 0.56839371244139928087e-2 * t480);
  t490 = sqrt(t387);
  t493 = POW_3_2(t387);
  t497 = t469 * t383 / t399;
  t503 = log(0.1e1 + 0.16081979498692535067e2 / (0.379785e1 * t490 + 0.8969e0 * t387 + 0.204775e0 * t493 + 0.123235e0 * t497));
  t505 = 0.621814e-1 * (0.1e1 + 0.53425e-1 * t387) * t503;
  t506 = 0.1e1 <= p->zeta_threshold;
  t507 = my_piecewise3(t506, t23, 1);
  t521 = log(0.1e1 + 0.29608749977793437516e2 / (0.51785e1 * t490 + 0.905775e0 * t387 + 0.1100325e0 * t493 + 0.1241775e0 * t497));
  t522 = (0.1e1 + 0.278125e-1 * t387) * t521;
  t525 = -t505 + 0.19751673498613801407e-1 * (0.2e1 * t507 - 0.2e1) * t431 * t522 + t391;
  t527 = my_piecewise3(-DBL_EPSILON < t525, -DBL_EPSILON, t525);
  t529 = (-0.36576794167600310304e-1 * t485 + 0.20989736912384607617e0) / t527;
  t532 = 0.5e1 / 0.36e2 * t387 * t463;
  t534 = my_piecewise3(DBL_EPSILON < t532, t532, DBL_EPSILON);
  t536 = (t464 - 0.1e1) / t534;
  t538 = my_piecewise3(0.e0 <= t536, t536, -t536);
  t541 = 0.3e1 / 0.16e2 * t470 * t529 * t538;
  t543 = 0.1e1 / t37;
  t544 = t466 < t541;
  t545 = my_piecewise3(t544, t541, t466);
  t549 = t545 * t545;
  t550 = t545 * t549;
  t554 = 0.1e1 / t116;
  t555 = t549 * t549;
  t565 = my_piecewise3(t544, t466, t541);
  t568 = atan(M_PI * t565 / 0.2e1);
  t571 = my_piecewise3(t466 <= t541, 0.1e1 - 0.4e1 * t543 / t545 + 0.16e2 / 0.3e1 * t94 / t550 - 0.64e2 / 0.5e1 * t554 / t545 / t555 + 0.256e3 / 0.7e1 * t129 / t550 / t555, 0.2e1 * t160 * t568);
  t575 = 0.3e1 / 0.16e2 * t470 * t529 * t536;
  t577 = t466 < t575;
  t578 = my_piecewise3(t577, t575, t466);
  t582 = t578 * t578;
  t583 = t578 * t582;
  t587 = t582 * t582;
  t597 = my_piecewise3(t577, t466, t575);
  t600 = atan(M_PI * t597 / 0.2e1);
  t603 = my_piecewise3(t466 <= t575, 0.1e1 - 0.4e1 * t543 / t578 + 0.16e2 / 0.3e1 * t94 / t583 - 0.64e2 / 0.5e1 * t554 / t578 / t587 + 0.256e3 / 0.7e1 * t129 / t583 / t587, 0.2e1 * t160 * t600);
  t604 = my_piecewise3(t464 < 0.e0, 0.2e1 + t571, t603);
  t608 = t428 * t431;
  t619 = log(0.1e1 + 0.32163958997385070134e2 / (0.705945e1 * t490 + 0.1549425e1 * t387 + 0.420775e0 * t493 + 0.1562925e0 * t497));
  t625 = t437 / t440 * t608 * (-0.310907e-1 * (0.1e1 + 0.5137e-1 * t387) * t619 + t505 - 0.19751673498613801407e-1 * t522);
  t627 = 0.19751673498613801407e-1 * t608 * t522;
  t629 = POW_1_3(0.16e2);
  t630 = t629 * t629;
  t632 = t22 * t22;
  t633 = my_piecewise3(t506, t632, 1);
  t634 = t633 * t633;
  t635 = t59 * t634;
  t637 = -0.70121174589195667679e-1 * t485 + 0.32022742560873636667e-1;
  t642 = log(0.2e1);
  t643 = 0.1e1 - t642;
  t644 = t643 * t543;
  t645 = t420 * t420;
  t646 = my_piecewise3(t419, t632, t645);
  t647 = t425 * t425;
  t648 = my_piecewise3(t424, t632, t647);
  t650 = t646 / 0.2e1 + t648 / 0.2e1;
  t651 = t650 * t650;
  t652 = t650 * t651;
  t653 = -t505 + t625 + t627;
  t654 = 0.1e1 / t643;
  t659 = exp(-t653 * t654 * t37 / t652);
  t660 = t659 - 0.1e1;
  t666 = 0.1e1 / t660;
  t670 = 0.1e1 / t27 / t398;
  t673 = t467 / t651;
  t675 = t37 * t666 * t397 * t670 * t416 * t673;
  t676 = t381 * t630 * t59 * t634 * t637 * t654 * t675;
  t677 = t676 / 0.32e2;
  t678 = 0.1e1 - t677;
  t680 = my_piecewise3(DBL_EPSILON < t678, t678, DBL_EPSILON);
  t681 = POW_1_4(t680);
  t687 = t634 * t634;
  t688 = t637 * t637;
  t690 = t643 * t643;
  t694 = t660 * t660;
  t697 = t397 * t397;
  t700 = 0.1e1 / t399 / t440;
  t701 = t416 * t416;
  t703 = t651 * t651;
  t704 = 0.1e1 / t703;
  t711 = 0.1e1 / (0.1e1 + 0.3e1 / 0.1024e4 * t468 * t629 * t82 * t687 * t688 / t690 * t93 / t694 * t697 * t700 * t701 * t704 * t3);
  t713 = 0.1e1 - 0.5e1 / 0.64e2 * t676;
  t715 = my_piecewise3(DBL_EPSILON < t713, t713, DBL_EPSILON);
  t719 = 0.1e1 + t660 * (0.1e1 - 0.1e1 / t681) * (0.1e1 - t711 + 0.1e1 / t715);
  t721 = my_piecewise3(DBL_MIN < t719, t719, DBL_MIN);
  t722 = log(t721);
  t725 = 0.1e1 + t677;
  t727 = my_piecewise3(DBL_EPSILON < t725, t725, DBL_EPSILON);
  t728 = POW_1_4(t727);
  t740 = 0.1e1 + (t659 + 0.185e1) * t381 * t630 * t635 * t637 * t654 * t675 / 0.128e3;
  t742 = my_piecewise3(DBL_EPSILON < t740, t740, DBL_EPSILON);
  t746 = 0.1e1 + t660 * (0.1e1 - 0.1e1 / t728) * (0.1e1 - t711 - 0.1e1 / t742);
  t748 = my_piecewise3(DBL_MIN < t746, t746, DBL_MIN);
  t749 = log(t748);
  t752 = my_piecewise3(0.e0 <= -0.3e1 / 0.16e2 * t468 * t384 * t630 * t635 * t637, t644 * t652 * t722, t644 * t652 * t749);
  t755 = t403 / 0.3e3;
  t758 = my_piecewise3(t755 < -t46, -t46, t755);
  t760 = exp(-0.1e1 / t758);
  t761 = my_piecewise3(t755 <= -t46, 0, t760);
  tzk1 = t446 + (0.1e1 - t604) * (-t505 + t625 + t627 + t752 - t446) * (0.1e1 - t761);

  t766 = 0.1e1 - t436 / t398;
  t769 = 0.1e1 / (0.1e1 + 0.349e0 * t385);
  t770 = t766 * t769;
  tzk2 = -0.4918e-1 * t770;

  t773 = exp(-0.2533e0 * t385);
  t774 = t773 * t769;
  t777 = (0.2533e0 + 0.349e0 * t769) * t385;
  tzk3 = -0.649176e-2 * t774 * t402 * (t766 * (0.47e2 - 0.7e1 * t777) / 0.72e2 - 0.2e1 / 0.3e1);

  t788 = p->zeta_threshold * p->zeta_threshold;
  t789 = t632 * t788;
  t790 = t418 * t418;
  t792 = my_piecewise3(t419, t789, t645 * t790);
  t793 = t423 * t423;
  t795 = my_piecewise3(t424, t789, t647 * t793);
  tzk4 = -0.973764e-3 * t774 * t467 * t58 * t766 * (t792 + t795);

  t800 = t774 * t416;
  t804 = t179 * t792;
  t805 = t343 * t795;
  tzk5 = 0.2028675e-3 * t800 * t766 * (0.5e1 / 0.2e1 - t777 / 0.18e2) * (t804 + t805);

  t812 = t632 * p->zeta_threshold * t788;
  t815 = my_piecewise3(t419, t812, t645 * t418 * t790);
  t819 = my_piecewise3(t424, t812, t647 * t423 * t793);
  tzk6 = 0.11270416666666666667e-4 * t800 * t766 * (t777 - 0.11e2) * (t179 * t815 + t343 * t819);

  t826 = my_piecewise3(t419, t788, t790);
  t831 = my_piecewise3(t424, t788, t793);
  tzk7 = -0.81147e-3 * t774 * t416 * (0.2e1 / 0.3e1 * t804 + 0.2e1 / 0.3e1 * t805 - t826 * sigma[2] * t342 * t795 / 0.4e1 - t831 * sigma[0] * t178 * t792 / 0.4e1);

  t842 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t28);
  t845 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t6 * t226);
  tzk8 = t842 + t845;

  t846 = t6 * t26;
  t848 = 0.3e1 / 0.1e2 * t36 * t58;
  t849 = t848 - t57;
  t851 = t848 + t57;
  t852 = 0.1e1 / t851;
  t856 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t27 * t849 * t852);
  t857 = t6 * t225;
  t858 = t848 - t246;
  t860 = t848 + t246;
  t861 = 0.1e1 / t860;
  t865 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t27 * t858 * t861);
  tzk9 = t856 + t865;

  t866 = t849 * t849;
  t868 = t851 * t851;
  t869 = 0.1e1 / t868;
  t873 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t27 * t866 * t869);
  t874 = t858 * t858;
  t876 = t860 * t860;
  t877 = 0.1e1 / t876;
  t881 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t27 * t874 * t877);
  tzk10 = t873 + t881;

  t882 = t849 * t866;
  t885 = 0.1e1 / t851 / t868;
  t889 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t27 * t882 * t885);
  t890 = t858 * t874;
  t893 = 0.1e1 / t860 / t876;
  t897 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t27 * t890 * t893);
  tzk11 = t889 + t897;

  t898 = t866 * t866;
  t900 = t868 * t868;
  t901 = 0.1e1 / t900;
  t905 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t27 * t898 * t901);
  t906 = t874 * t874;
  t908 = t876 * t876;
  t909 = 0.1e1 / t908;
  t913 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t27 * t906 * t909);
  tzk12 = t905 + t913;

  t921 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t27 * t849 * t898 / t851 / t900);
  t929 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t27 * t858 * t906 / t860 / t908);
  tzk13 = t921 + t929;

  t930 = t3 * t26;
  t931 = t930 * t27;
  t933 = 0.1e1 + 0.4e-2 * t179;
  t934 = 0.1e1 / t933;
  t938 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t931 * t179 * t934);
  t939 = t3 * t225;
  t940 = t939 * t27;
  t942 = 0.1e1 + 0.4e-2 * t343;
  t943 = 0.1e1 / t942;
  t947 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t940 * t343 * t943);
  tzk14 = t938 + t947;

  t949 = t930 * t27 * sigma[0];
  t950 = t178 * t934;
  t951 = t849 * t852;
  t955 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t951);
  t957 = t939 * t27 * sigma[2];
  t958 = t342 * t943;
  t959 = t858 * t861;
  t963 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t959);
  tzk15 = t955 + t963;

  t964 = t866 * t869;
  t968 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t964);
  t969 = t874 * t877;
  t973 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t969);
  tzk16 = t968 + t973;

  t974 = t882 * t885;
  t978 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t974);
  t979 = t890 * t893;
  t983 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t979);
  tzk17 = t978 + t983;

  t984 = t898 * t901;
  t988 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t984);
  t989 = t906 * t909;
  t993 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t989);
  tzk18 = t988 + t993;

  t994 = t933 * t933;
  t995 = 0.1e1 / t994;
  t999 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t931 * t185 * t995);
  t1000 = t942 * t942;
  t1001 = 0.1e1 / t1000;
  t1005 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t940 * t349 * t1001);
  tzk19 = t999 + t1005;

  t1007 = t930 * t27 * t182;
  t1008 = t184 * t995;
  t1012 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t1007 * t1008 * t951);
  t1014 = t939 * t27 * t346;
  t1015 = t348 * t1001;
  t1019 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t1014 * t1015 * t959);
  tzk20 = t1012 + t1019;

  t1023 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t1007 * t1008 * t964);
  t1027 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t1014 * t1015 * t969);
  tzk21 = t1023 + t1027;

  t1031 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t1007 * t1008 * t974);
  t1035 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t1014 * t1015 * t979);
  tzk22 = t1031 + t1035;

  t1036 = sigma[0] * t182;
  t1037 = 0.1e1 / t112;
  t1040 = 0.1e1 / t933 / t994;
  t1044 = my_piecewise3(t2, 0, -0.16386817518127096355e-7 * t931 * t1036 * t1037 * t1040);
  t1045 = sigma[2] * t346;
  t1046 = 0.1e1 / t290;
  t1049 = 0.1e1 / t942 / t1000;
  t1053 = my_piecewise3(t217, 0, -0.16386817518127096355e-7 * t940 * t1045 * t1046 * t1049);
  tzk23 = t1044 + t1053;

  t1055 = t930 * t27 * t1036;
  t1056 = t1037 * t1040;
  t1060 = my_piecewise3(t2, 0, -0.16386817518127096355e-7 * t1055 * t1056 * t951);
  t1062 = t939 * t27 * t1045;
  t1063 = t1046 * t1049;
  t1067 = my_piecewise3(t217, 0, -0.16386817518127096355e-7 * t1062 * t1063 * t959);
  tzk24 = t1060 + t1067;

  t1071 = my_piecewise3(t2, 0, -0.16386817518127096355e-7 * t1055 * t1056 * t964);
  t1075 = my_piecewise3(t217, 0, -0.16386817518127096355e-7 * t1062 * t1063 * t969);
  tzk25 = t1071 + t1075;

  t1076 = t385 * t416;
  t1077 = my_piecewise5(t419, t12, t424, t16, t18);
  t1080 = POW_1_3(0.1e1 / (0.1e1 + t1077));
  t1083 = 0.1e1 + 0.39999999999999999998e0 * t1076 * t1080;
  t1084 = 0.1e1 / t1083;
  t1088 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t28 * t1084);
  t1089 = my_piecewise5(t424, t12, t419, t16, -t18);
  t1092 = POW_1_3(0.1e1 / (0.1e1 + t1089));
  t1095 = 0.1e1 + 0.39999999999999999998e0 * t1076 * t1092;
  t1096 = 0.1e1 / t1095;
  t1100 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t6 * t226 * t1096);
  tzk26 = t1088 + t1100;

  t1101 = t27 * t1084;
  t1105 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1101 * t951);
  t1106 = t27 * t1096;
  t1110 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1106 * t959);
  tzk27 = t1105 + t1110;

  t1114 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1101 * t964);
  t1118 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1106 * t969);
  tzk28 = t1114 + t1118;

  t1122 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1101 * t974);
  t1126 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1106 * t979);
  tzk29 = t1122 + t1126;

  t1130 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1101 * t984);
  t1134 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1106 * t989);
  tzk30 = t1130 + t1134;

  t1139 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t931 * t179 * t934 * t1084);
  t1144 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t940 * t343 * t943 * t1096);
  tzk31 = t1139 + t1144;

  t1146 = t1084 * t849 * t852;
  t1150 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t1146);
  t1152 = t1096 * t858 * t861;
  t1156 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t1152);
  tzk32 = t1150 + t1156;

  t1158 = t1084 * t866 * t869;
  t1162 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t1158);
  t1164 = t1096 * t874 * t877;
  t1168 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t1164);
  tzk33 = t1162 + t1168;

  t1174 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t1084 * t882 * t885);
  t1180 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t1096 * t890 * t893);
  tzk34 = t1174 + t1180;

  t1185 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t931 * t185 * t995 * t1084);
  t1190 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t940 * t349 * t1001 * t1096);
  tzk35 = t1185 + t1190;

  t1194 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t1007 * t1008 * t1146);
  t1198 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t1014 * t1015 * t1152);
  tzk36 = t1194 + t1198;

  t1202 = my_piecewise3(t2, 0, -0.40967043795317740888e-5 * t1007 * t1008 * t1158);
  t1206 = my_piecewise3(t217, 0, -0.40967043795317740888e-5 * t1014 * t1015 * t1164);
  tzk37 = t1202 + t1206;

  t1207 = t1083 * t1083;
  t1208 = 0.1e1 / t1207;
  t1212 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t28 * t1208);
  t1213 = t1095 * t1095;
  t1214 = 0.1e1 / t1213;
  t1218 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t6 * t226 * t1214);
  tzk38 = t1212 + t1218;

  t1219 = t27 * t1208;
  t1223 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1219 * t951);
  t1224 = t27 * t1214;
  t1228 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1224 * t959);
  tzk39 = t1223 + t1228;

  t1232 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1219 * t964);
  t1236 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1224 * t969);
  tzk40 = t1232 + t1236;

  t1240 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1219 * t974);
  t1244 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1224 * t979);
  tzk41 = t1240 + t1244;

  t1249 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t931 * t179 * t934 * t1208);
  t1254 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t940 * t343 * t943 * t1214);
  tzk42 = t1249 + t1254;

  t1260 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t1208 * t849 * t852);
  t1266 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t1214 * t858 * t861);
  tzk43 = t1260 + t1266;

  t1272 = my_piecewise3(t2, 0, -0.10241760948829435222e-2 * t949 * t950 * t1208 * t866 * t869);
  t1278 = my_piecewise3(t217, 0, -0.10241760948829435222e-2 * t957 * t958 * t1214 * t874 * t877);
  tzk44 = t1272 + t1278;

  t1280 = 0.1e1 / t1083 / t1207;
  t1284 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t28 * t1280);
  t1286 = 0.1e1 / t1095 / t1213;
  t1290 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t6 * t226 * t1286);
  tzk45 = t1284 + t1290;

  t1291 = t27 * t1280;
  t1295 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1291 * t951);
  t1296 = t27 * t1286;
  t1300 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1296 * t959);
  tzk46 = t1295 + t1300;

  t1304 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t846 * t1291 * t964);
  t1308 = my_piecewise3(t217, 0, -0.3e1 / 0.8e1 * t857 * t1296 * t969);
  tzk47 = t1304 + t1308;

  tzk48 = t653;

  t1310 = t701 * (t451 + t456);
  t1311 = t848 - t1310;
  t1312 = t848 + t1310;
  t1314 = t1311 / t1312;
  tzk49 = t1314 * tzk48;

  t1315 = t1311 * t1311;
  t1316 = t1312 * t1312;
  t1318 = t1315 / t1316;
  tzk50 = t1318 * tzk48;

  t1319 = t1311 * t1315;
  t1320 = t1312 * t1316;
  t1322 = t1319 / t1320;
  tzk51 = t1322 * tzk48;

  t1323 = t1315 * t1315;
  t1324 = t1316 * t1316;
  t1326 = t1323 / t1324;
  tzk52 = t1326 * tzk48;

  t1330 = t1311 * t1323 / t1312 / t1324;
  tzk53 = t1330 * tzk48;

  t1334 = t1315 * t1323 / t1316 / t1324;
  tzk54 = t1334 * tzk48;

  t1338 = t1319 * t1323 / t1320 / t1324;
  tzk55 = t1338 * tzk48;

  t1339 = t1323 * t1323;
  t1340 = t1324 * t1324;
  t1342 = t1339 / t1340;
  tzk56 = t1342 * tzk48;

  t1350 = t654 * t666;
  t1360 = t397 * t670 * t416 * t673 / t381 * t383 / 0.96e2 + 0.21437009059034868486e-3 * t1350 * t697 * t700 * t701 * t704 * t3 / t468 * t384;
  t1369 = log(0.1e1 + 0.65854491829355115987e0 * t1360 * t654 / (0.1e1 + 0.65854491829355115987e0 * t1350 * t1360));
  tzk57 = t644 * t652 * t1369;

  t1373 = t543 * t652 * t1369;
  tzk58 = t1314 * t643 * t1373;

  tzk59 = t1318 * t643 * t1373;

  tzk60 = t1322 * t643 * t1373;

  tzk61 = t1326 * t643 * t1373;

  tzk62 = t1330 * t643 * t1373;

  tzk63 = t1334 * t643 * t1373;

  tzk64 = t1338 * t643 * t1373;

  tzk65 = t1342 * t643 * t1373;

  t1381 = my_piecewise3(t419, p->zeta_threshold, t418);
  t1384 = 0.1e1 / (t31 + 0.349e0);
  t1387 = my_piecewise3(t424, p->zeta_threshold, t423);
  t1390 = 0.1e1 / (t228 + 0.349e0);
  tzk66 = -0.94485e-2 * t1381 * t31 * t1384 - 0.94485e-2 * t1387 * t228 * t1390;

  t1397 = POW_2(0.1e1 + 0.6e-2 * t179);
  t1406 = POW_2(0.1e1 + 0.6e-2 * t343);
  tzk67 = 0.279432e-5 * t1381 * t91 * t1384 * t182 / t1397 + 0.279432e-5 * t1387 * t274 * t1390 * t346 / t1406;

  t1417 = POW_2(0.1e1 + 0.6e-2 * t402);
  tzk68 = t770 * (-0.159068e0 + 0.286308e-6 * t697 / t27 / t7 / t440 / t1417) / 0.4e1;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC)) {
    out->zk[ip*p->dim.zk + 0] += tzk0;
    out->zk[ip*p->dim.zk + 1] += tzk1;
    out->zk[ip*p->dim.zk + 2] += tzk2;
    out->zk[ip*p->dim.zk + 3] += tzk3;
    out->zk[ip*p->dim.zk + 4] += tzk4;
    out->zk[ip*p->dim.zk + 5] += tzk5;
    out->zk[ip*p->dim.zk + 6] += tzk6;
    out->zk[ip*p->dim.zk + 7] += tzk7;
    out->zk[ip*p->dim.zk + 8] += tzk8;
    out->zk[ip*p->dim.zk + 9] += tzk9;
    out->zk[ip*p->dim.zk + 10] += tzk10;
    out->zk[ip*p->dim.zk + 11] += tzk11;
    out->zk[ip*p->dim.zk + 12] += tzk12;
    out->zk[ip*p->dim.zk + 13] += tzk13;
    out->zk[ip*p->dim.zk + 14] += tzk14;
    out->zk[ip*p->dim.zk + 15] += tzk15;
    out->zk[ip*p->dim.zk + 16] += tzk16;
    out->zk[ip*p->dim.zk + 17] += tzk17;
    out->zk[ip*p->dim.zk + 18] += tzk18;
    out->zk[ip*p->dim.zk + 19] += tzk19;
    out->zk[ip*p->dim.zk + 20] += tzk20;
    out->zk[ip*p->dim.zk + 21] += tzk21;
    out->zk[ip*p->dim.zk + 22] += tzk22;
    out->zk[ip*p->dim.zk + 23] += tzk23;
    out->zk[ip*p->dim.zk + 24] += tzk24;
    out->zk[ip*p->dim.zk + 25] += tzk25;
    out->zk[ip*p->dim.zk + 26] += tzk26;
    out->zk[ip*p->dim.zk + 27] += tzk27;
    out->zk[ip*p->dim.zk + 28] += tzk28;
    out->zk[ip*p->dim.zk + 29] += tzk29;
    out->zk[ip*p->dim.zk + 30] += tzk30;
    out->zk[ip*p->dim.zk + 31] += tzk31;
    out->zk[ip*p->dim.zk + 32] += tzk32;
    out->zk[ip*p->dim.zk + 33] += tzk33;
    out->zk[ip*p->dim.zk + 34] += tzk34;
    out->zk[ip*p->dim.zk + 35] += tzk35;
    out->zk[ip*p->dim.zk + 36] += tzk36;
    out->zk[ip*p->dim.zk + 37] += tzk37;
    out->zk[ip*p->dim.zk + 38] += tzk38;
    out->zk[ip*p->dim.zk + 39] += tzk39;
    out->zk[ip*p->dim.zk + 40] += tzk40;
    out->zk[ip*p->dim.zk + 41] += tzk41;
    out->zk[ip*p->dim.zk + 42] += tzk42;
    out->zk[ip*p->dim.zk + 43] += tzk43;
    out->zk[ip*p->dim.zk + 44] += tzk44;
    out->zk[ip*p->dim.zk + 45] += tzk45;
    out->zk[ip*p->dim.zk + 46] += tzk46;
    out->zk[ip*p->dim.zk + 47] += tzk47;
    out->zk[ip*p->dim.zk + 48] += tzk48;
    out->zk[ip*p->dim.zk + 49] += tzk49;
    out->zk[ip*p->dim.zk + 50] += tzk50;
    out->zk[ip*p->dim.zk + 51] += tzk51;
    out->zk[ip*p->dim.zk + 52] += tzk52;
    out->zk[ip*p->dim.zk + 53] += tzk53;
    out->zk[ip*p->dim.zk + 54] += tzk54;
    out->zk[ip*p->dim.zk + 55] += tzk55;
    out->zk[ip*p->dim.zk + 56] += tzk56;
    out->zk[ip*p->dim.zk + 57] += tzk57;
    out->zk[ip*p->dim.zk + 58] += tzk58;
    out->zk[ip*p->dim.zk + 59] += tzk59;
    out->zk[ip*p->dim.zk + 60] += tzk60;
    out->zk[ip*p->dim.zk + 61] += tzk61;
    out->zk[ip*p->dim.zk + 62] += tzk62;
    out->zk[ip*p->dim.zk + 63] += tzk63;
    out->zk[ip*p->dim.zk + 64] += tzk64;
    out->zk[ip*p->dim.zk + 65] += tzk65;
    out->zk[ip*p->dim.zk + 66] += tzk66;
    out->zk[ip*p->dim.zk + 67] += tzk67;
    out->zk[ip*p->dim.zk + 68] += tzk68;
  }

}

#endif

