#!/usr/bin/env python3
"""Generate the private libifxc ML25 generated source wrapper.

The checked-in generated C/header pair and the generate target keep the
milestone workflow aligned with PLAN.md while the combined Maple source of
truth is being reintroduced.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


FEATURE_DEF_RE = re.compile(
    r'^IFXC_ML25_FEATURE\(\s*(\d+)\s*,\s*([A-Z0-9_]+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*(IFXC_FEATURE_KIND_[A-Z_]+)\s*\)\s*$'
)
INCLUDE_RE = re.compile(r'^\$include\s+"([^"]+)"\s*$')
ASSIGN_RE = re.compile(r'^([a-z0-9_]+)\s*:=\s*f:\s*$')
MAPLE_KEY_RE = re.compile(r'#\s*(\d+)\s*,\s*(ml25\.[a-z0-9_]+)\s*$')

REQUIRED_SUPPORT_FILES = [
    Path("maple/util.mpl"),
    Path("maple/lda_exc/lda_x.mpl"),
    Path("maple/lda_exc/lda_c_pw.mpl"),
    Path("maple/gga_exc/gga_c_lyp.mpl"),
    Path("maple/gga_exc/gga_c_pbe.mpl"),
    Path("maple/mgga_exc/mgga_x_mn12.mpl"),
    Path("maple/mgga_exc/mgga_c_m08.mpl"),
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def parse_feature_def(path: Path) -> list[tuple[int, str, str, str, str]]:
    features: list[tuple[int, str, str, str, str]] = []
    for line in read_text(path).splitlines():
        line = line.strip()
        if not line or line.startswith("/*"):
            continue
        match = FEATURE_DEF_RE.match(line)
        if match:
            index = int(match.group(1))
            feature_name = match.group(2)
            feature_key = match.group(3)
            feature_group = match.group(4)
            feature_kind = match.group(5)
            features.append((index, feature_name, feature_key, feature_group, feature_kind))
    return features


def maple_include_for_key(feature_key: str) -> str:
    suffix = feature_key.split(".", 1)[1]
    if suffix == "lak_x":
        return "mgga_exc/mgga_x_lak.mpl"
    if suffix == "lak_c":
        return "mgga_exc/mgga_c_lak.mpl"
    return f"mgga_exc/mgga_xc_ml25_{suffix}.mpl"


def maple_binding_for_key(feature_key: str) -> str:
    suffix = feature_key.split(".", 1)[1]
    return f"{suffix}_h"


def parse_maple_formula_entries(path: Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    current_include: str | None = None
    for raw_line in read_text(path).splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("ifxc_ml25_features := ["):
            break
        include_match = INCLUDE_RE.match(line)
        if include_match:
            current_include = include_match.group(1)
            continue
        assign_match = ASSIGN_RE.match(line)
        if assign_match and current_include is not None:
            entries.append((current_include, assign_match.group(1)))
            current_include = None
            continue
    return entries


def parse_maple_keys(path: Path) -> list[tuple[int, str]]:
    keys: list[tuple[int, str]] = []
    in_vector = False
    for raw_line in read_text(path).splitlines():
        line = raw_line.strip()
        if line.startswith("ifxc_ml25_features := ["):
            in_vector = True
            continue
        if not in_vector:
            continue
        if line.startswith("]:"):
            break
        if not line or line.startswith("#"):
            continue
        match = MAPLE_KEY_RE.search(raw_line)
        if match:
            keys.append((int(match.group(1)), match.group(2)))
    return keys


def emit_header() -> str:
    return """/* Generated by scripts/maple2c_ifxc.py from maple/mgga_xc_ml25.mpl. Do not edit by hand. */
#ifndef IFXC_MGGA_XC_ML25_FEATURES_H
#define IFXC_MGGA_XC_ML25_FEATURES_H

#include "ifxc.h"

#define IFXC_ML25_GENERATED_FEATURE_COUNT IFXC_ML25_NFEATURES

extern const char *const ifxc_ml25_generated_feature_keys[IFXC_ML25_NFEATURES];

#endif /* IFXC_MGGA_XC_ML25_FEATURES_H */
"""


def emit_source(feature_keys: list[str]) -> str:
    lines = [
        "/* Generated by scripts/maple2c_ifxc.py from maple/mgga_xc_ml25.mpl. Do not edit by hand. */",
        "",
        '#include "ifxc_mgga_xc_ml25_features.h"',
        "",
        "const char *const ifxc_ml25_generated_feature_keys[IFXC_ML25_NFEATURES] = {",
    ]
    for key in feature_keys:
        lines.append(f'  "{key}",')
    lines.extend(
        [
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True)
    parser.add_argument("--feature-def", required=True)
    parser.add_argument("--feature-set", required=True)
    parser.add_argument("--max-deriv-order", required=True, type=int)
    parser.add_argument("--output-c", required=True)
    parser.add_argument("--output-h", required=True)
    args = parser.parse_args(argv)

    source_path = Path(args.source)
    feature_def_path = Path(args.feature_def)
    output_c_path = Path(args.output_c)
    output_h_path = Path(args.output_h)

    if args.feature_set != "ml25":
        raise SystemExit(f"unsupported feature set: {args.feature_set}")
    if args.max_deriv_order != 4:
        raise SystemExit("expected ML25 max derivative order 4")

    source_text = read_text(source_path)
    if "ifxc_feature_count := 66:" not in source_text:
        raise SystemExit("maple source does not advertise a 66-feature vector")

    feature_defs = parse_feature_def(feature_def_path)
    if len(feature_defs) != 66:
        raise SystemExit(f"expected 66 feature definitions, found {len(feature_defs)}")
    if [item[0] for item in feature_defs] != list(range(66)):
        raise SystemExit("feature definition indexes are not contiguous")

    maple_keys = parse_maple_keys(source_path)
    if len(maple_keys) != 66:
        raise SystemExit(f"expected 66 Maple feature entries, found {len(maple_keys)}")
    if [item[0] for item in maple_keys] != list(range(66)):
        raise SystemExit("Maple feature indexes are not contiguous")

    maple_entries = parse_maple_formula_entries(source_path)
    if len(maple_entries) != 66:
        raise SystemExit(f"expected 66 Maple feature includes, found {len(maple_entries)}")

    feature_keys = [item[2] for item in feature_defs]
    maple_feature_keys = [item[1] for item in maple_keys]
    if feature_keys != maple_feature_keys:
        raise SystemExit("feature def keys and Maple feature keys differ")

    expected_includes = [maple_include_for_key(key) for key in feature_keys]
    expected_bindings = [maple_binding_for_key(key) for key in feature_keys]
    actual_includes = [item[0] for item in maple_entries]
    actual_bindings = [item[1] for item in maple_entries]
    if actual_includes != expected_includes:
        raise SystemExit("Maple include list differs from feature definitions")
    if actual_bindings != expected_bindings:
        raise SystemExit("Maple binding list differs from feature definitions")
    for include_path in expected_includes:
        if not (source_path.parent / include_path).exists():
            raise SystemExit(f"missing Maple include: {include_path}")

    for support_path in REQUIRED_SUPPORT_FILES:
        if not support_path.exists():
            raise SystemExit(f"missing Maple support file: {support_path}")

    source_text = emit_source(feature_keys)
    if not source_text.endswith("\n"):
        source_text += "\n"

    write_if_changed(output_h_path, emit_header())
    write_if_changed(output_c_path, source_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
