/*
  This file was generated automatically with scripts/maple2c.py.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2025 (X86 64 LINUX)
  Maple source      : maple/mgga_xc_ml25.mpl
  Type of functional: mgga_exc
*/

#define maple2c_order 0
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC)


#ifndef XC_DONT_COMPILE_EXC
GPU_DEVICE_FUNCTION static inline void
func_exc_unpol(const xc_func_type *p, size_t ip, const double *rho, const double *sigma, const double *lapl, const double *tau, xc_mgga_out_params *out)
{ 
  double t3, t4, t5, t6, t8, t9, t10, t11;
  double t13, t14, t16, t17, t18, t20, t21, t22;
  double t23, t24, t25, t26, t27, t28, t29, t30;
  double t34, t35, t37, t38, t42, t44, t45, t46;
  double t49, t51, t52, t53, t54, t56, t58, t59;
  double t60, t61, t62, t67, t71, t73, t74, t77;
  double t79, t80, t85, t87, t91, t92, t93, t94;
  double t96, t97, t98, t102, t111, t117, t121, t133;
  double t134, t152, t162, t168, t169, t173, t178, t181;
  double t183, t185, t188, t189, t190, t197, t198, t203;
  double t206, t208, t209, t214, t217, t219, t220, t228;
  double tzk0, t230, t231, t233, t236, t237, t239, t242;
  double t243, t246, t250, t252, t253, t256, t257, t259;
  double t262, t266, t272, t273, t275, t276, t277, t278;
  double t279, t281, t284, t289, t294, t299, t300, t301;
  double t304, t308, t314, t316, t328, t331, t332, t334;
  double t336, t339, t341, t343, t345, t348, t350, t351;
  double t352, t356, t357, t361, t362, t372, t375, t378;
  double t382, t384, t385, t389, t390, t394, t404, t407;
  double t410, t411, t414, t415, t417, t418, t419, t422;
  double t427, t428, t429, t430, t431, t432, t437, t438;
  double t441, t443, t447, t450, t451, t452, t453, t455;
  double t456, t461, t463, t467, t472, t479, t481, t483;
  double t487, t489, t490, t493, t495, t496, t506, t508;
  double t512, t514, t515, t518, t521, t524, t526, t527;
  double tzk1, t532, tzk2, t535, t536, t539, tzk3, t546;
  double t548, tzk4, tzk5, t561, tzk6, t567, tzk7, t578;
  double t579, t583, tzk8, t585, t586, t588, t589, t594;
  double tzk9, t595, t597, t598, t603, tzk10, t604, t606;
  double t607, t612, tzk11, t613, t615, t616, t621, tzk12;
  double t622, t625, t630, tzk13, t631, t635, t636, t637;
  double t641, tzk14, t642, t649, tzk15, t656, tzk16, t663;
  double tzk17, t670, tzk18, t671, t672, t673, t674, t675;
  double t676, t680, tzk19, t681, t682, t683, t689, tzk20;
  double t690, t696, tzk21, t703, tzk22, t704, t708, t710;
  double t712, t717, tzk23, t718, t725, tzk24, t732, tzk25;
  double t735, t738, t739, t744, tzk26, t746, t747, t752;
  double tzk27, t753, t758, tzk28, t759, t764, tzk29, t765;
  double t770, tzk30, t771, t776, tzk31, t778, t779, t783;
  double tzk32, t787, tzk33, t791, tzk34, t792, t796, tzk35;
  double t801, tzk36, t806, tzk37, t807, t808, t813, tzk38;
  double t818, tzk39, t823, tzk40, t828, tzk41, t833, tzk42;
  double t834, t838, tzk43, t842, tzk44, t844, t849, tzk45;
  double t854, tzk46, t859, tzk47, tzk48, tzk49, tzk50, tzk51;
  double tzk52, t860, tzk53, t864, tzk54, t868, tzk55, t869;
  double t870, t872, tzk56, t879, t882, t891, t900, tzk57;
  double t904, tzk58, tzk59, tzk60, tzk61, tzk62, tzk63, tzk64;
  double tzk65;

  t3 = rho[0] / 0.2e1 <= p->dens_threshold;
  t4 = M_CBRT3;
  t5 = M_CBRTPI;
  t6 = t5 * t5;
  t8 = t4 / t6;
  t9 = M_CBRT2;
  t10 = 0.1e1 <= p->zeta_threshold;
  t11 = p->zeta_threshold - 0.1e1;
  t13 = my_piecewise5(t10, t11, t10, -t11, 0);
  t14 = 0.1e1 + t13;
  t16 = POW_1_3(p->zeta_threshold);
  t17 = t16 * p->zeta_threshold;
  t18 = POW_1_3(t14);
  t20 = my_piecewise3(t14 <= p->zeta_threshold, t17, t18 * t14);
  t21 = t9 * t20;
  t22 = t8 * t21;
  t23 = 0.1e1 / M_PI;
  t24 = POW_1_3(t23);
  t25 = 0.1e1 / t24;
  t26 = M_CBRT4;
  t27 = t25 * t26;
  t28 = POW_1_3(rho[0]);
  t29 = sqrt(0.3e1);
  t30 = sqrt(sigma[0]);
  t34 = M_CBRT6;
  t35 = t34 * t34;
  t37 = M_PI * M_PI;
  t38 = POW_1_3(t37);
  t42 = sqrt(t30 * t9 / t28 / rho[0] * t35 / t38);
  t44 = 0.33684323989301858702e-1 * t29 * t42;
  t45 = log(DBL_EPSILON);
  t46 = 0.1e1 / t45;
  t49 = my_piecewise3(t44 < -t46, -t46, t44);
  t51 = exp(-0.1e1 / t49);
  t52 = my_piecewise3(t44 <= -t46, 0, t51);
  t53 = 0.1174e1 * t52;
  t54 = t9 * t9;
  t56 = t28 * t28;
  t58 = 0.1e1 / t56 / rho[0];
  t59 = tau[0] * t54 * t58;
  t60 = t38 * t38;
  t61 = 0.1e1 / t60;
  t62 = t34 * t61;
  t67 = sigma[0] / rho[0] / tau[0] / 0.8e1;
  t71 = my_piecewise3(0.e0 < 0.9999999999e0 - t67, 0.1e1 - t67, 0.1e-9);
  t73 = t59 * t62 * t71;
  t74 = 0.5e1 / 0.9e1 * t73;
  t77 = tau[0] * tau[0];
  t79 = rho[0] * rho[0];
  t80 = t79 * rho[0];
  t85 = 0.1e1 / t38 / t37;
  t87 = t71 * t71;
  t91 = t77 * tau[0];
  t92 = t79 * t79;
  t93 = t92 * rho[0];
  t94 = 0.1e1 / t93;
  t96 = t37 * t37;
  t97 = 0.1e1 / t96;
  t98 = t87 * t71;
  t102 = t77 * t77;
  t111 = t87 * t87;
  t117 = t92 * t92;
  t121 = t96 * t37;
  t133 = t96 * t96;
  t134 = 0.1e1 / t133;
  t152 = t102 * t102;
  t162 = t111 * t111;
  t168 = my_piecewise3(DBL_EPSILON < t74, t74, DBL_EPSILON);
  t169 = t168 - 0.1e1;
  t173 = t169 * t169;
  t178 = atan(M_PI * (-0.12063067191025636561e1 * t169 / t168 - 0.11103356059345265253e1 * t173) / 0.2e1);
  t181 = my_piecewise3(t74 <= DBL_EPSILON, 0.99999999999999999996e0 - 0.18665085944258768548e0 * t73 - 0.3982802071644629979e0 * t77 * t9 / t28 / t80 * t35 * t85 * t87 - 0.24255988786338671402e1 * t91 * t94 * t97 * t98 - 0.30550082955089596463e0 * t102 * t54 / t56 / t92 / t79 * t34 / t60 / t96 * t111 + 0.11675206820539006889e1 * t102 * tau[0] * t9 / t28 / t117 * t35 / t38 / t121 * t111 * t71 + 0.13980660423962914871e2 * t102 * t77 / t117 / t79 * t134 * t111 * t87 + 0.65062566833713102403e1 * t102 * t91 * t54 / t56 / t117 / t80 * t34 / t60 / t133 * t111 * t98 - 0.14122917874011873194e-1 * t152 * t9 / t28 / t117 / t93 * t35 / t38 / t133 / t37 * t162, 0.2e1 * t23 * t178);
  t183 = sigma[0] * t54;
  t185 = 0.1e1 / t56 / t79;
  t188 = t183 * t185 * t34 * t61;
  t189 = 0.13342809400364015279e-2 * t188;
  t190 = sigma[0] * sigma[0];
  t197 = 0.30797417856580405118e-3 * t190 * t9 / t28 / t93 * t35 * t85;
  t198 = t183 * t185;
  t203 = 0.34435261707988980717e-1 * t198 * t62 * (0.1e1 + t188 / 0.24e2);
  t206 = my_piecewise3(t203 < -t46, -t46, t203);
  t208 = exp(-0.1e1 / t206);
  t209 = my_piecewise3(t203 <= -t46, 0, t208);
  t214 = t188 / 0.6e3;
  t217 = my_piecewise3(t214 < -t46, -t46, t214);
  t219 = exp(-0.1e1 / t217);
  t220 = my_piecewise3(t214 <= -t46, 0, t219);
  t228 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * (0.1174e1 - t53 + (0.1e1 - t181) * (-0.174e0 - t189 - t197 + t53 + t209 * (0.1e0 + t189 + t197 - t53)) * (0.1e1 - t220)));
  tzk0 = 0.2e1 * t228;

  t230 = t26 * t26;
  t231 = 0.1e1 / t28;
  t233 = t4 * t24 * t230 * t231;
  t236 = 0.1e1 / (0.1e1 + 0.5140025e-1 * t233);
  t237 = 0.468e-1 * t236;
  t239 = exp(0.1e1 * t236);
  t242 = sigma[0] * t185;
  t243 = t4 * t61 * t242;
  t246 = POW_1_4(0.1e1 + 0.51781333333333333332e0 * t243);
  t250 = 0.1e1 + (t239 - 0.1e1) * (0.1e1 - 0.1e1 / t246);
  t252 = my_piecewise3(t250 < DBL_MIN, DBL_MIN, t250);
  t253 = log(t252);
  t256 = t9 - 0.1e1;
  t257 = my_piecewise3(t10, t17, 1);
  t259 = 0.2e1 * t257 - 0.2e1;
  t262 = 0.1e1 / t256 / 0.2e1;
  t266 = (-t237 + 0.468e-1 * t253) * (0.1e1 - 0.23631e1 * t256 * t259 * t262);
  t272 = (tau[0] * t58 - t242 / 0.8e1) * t34 * t61 * t54;
  t273 = 0.5e1 / 0.9e1 * t272;
  t275 = 0.1e1 / DBL_EPSILON;
  t276 = t4 * t4;
  t277 = t24 * t24;
  t278 = t276 * t277;
  t279 = t278 * t230;
  t281 = pow(t233, 0.65e0);
  t284 = pow(t233, 0.9e0);
  t289 = pow(t233, 0.12e1);
  t294 = t4 * t38 * (0.1e1 + 0.4061261981781177613e-1 * t281) / (0.1e1 + 0.1866634826870181886e-1 * t284) / (0.1e1 + 0.56839371244139928087e-2 * t289);
  t299 = sqrt(0.4e1);
  t300 = sqrt(t233);
  t301 = t299 * t300;
  t304 = POW_3_2(t233);
  t308 = t278 * t26 / t56;
  t314 = log(0.1e1 + 0.16081979498692535067e2 / (0.1898925e1 * t301 + 0.8969e0 * t233 + 0.204775e0 * t304 + 0.123235e0 * t308));
  t316 = 0.621814e-1 * (0.1e1 + 0.53425e-1 * t233) * t314;
  t328 = log(0.1e1 + 0.29608749977793437516e2 / (0.258925e1 * t301 + 0.905775e0 * t233 + 0.1100325e0 * t304 + 0.1241775e0 * t308));
  t331 = 0.19751673498613801407e-1 * t259 * t262 * (0.1e1 + 0.278125e-1 * t233) * t328;
  t332 = -t316 + t331 + t237;
  t334 = my_piecewise3(-DBL_EPSILON < t332, -DBL_EPSILON, t332);
  t336 = (-0.36576794167600310304e-1 * t294 + 0.20989736912384607617e0) / t334;
  t339 = 0.5e1 / 0.36e2 * t233 * t272;
  t341 = my_piecewise3(DBL_EPSILON < t339, t339, DBL_EPSILON);
  t343 = (t273 - 0.1e1) / t341;
  t345 = my_piecewise3(0.e0 <= t343, t343, -t343);
  t348 = 0.3e1 / 0.16e2 * t279 * t336 * t345;
  t350 = 0.1e1 / t37;
  t351 = t275 < t348;
  t352 = my_piecewise3(t351, t348, t275);
  t356 = t352 * t352;
  t357 = t356 * t352;
  t361 = 0.1e1 / t121;
  t362 = t356 * t356;
  t372 = my_piecewise3(t351, t275, t348);
  t375 = atan(M_PI * t372 / 0.2e1);
  t378 = my_piecewise3(t275 <= t348, 0.1e1 - 0.4e1 * t350 / t352 + 0.16e2 / 0.3e1 * t97 / t357 - 0.64e2 / 0.5e1 * t361 / t362 / t352 + 0.256e3 / 0.7e1 * t134 / t362 / t357, 0.2e1 * t23 * t375);
  t382 = 0.3e1 / 0.16e2 * t279 * t336 * t343;
  t384 = t275 < t382;
  t385 = my_piecewise3(t384, t382, t275);
  t389 = t385 * t385;
  t390 = t389 * t385;
  t394 = t389 * t389;
  t404 = my_piecewise3(t384, t275, t382);
  t407 = atan(M_PI * t404 / 0.2e1);
  t410 = my_piecewise3(t275 <= t382, 0.1e1 - 0.4e1 * t350 / t385 + 0.16e2 / 0.3e1 * t97 / t390 - 0.64e2 / 0.5e1 * t361 / t394 / t385 + 0.256e3 / 0.7e1 * t134 / t394 / t390, 0.2e1 * t23 * t407);
  t411 = my_piecewise3(t273 < 0.e0, 0.2e1 + t378, t410);
  t414 = POW_1_3(0.16e2);
  t415 = t414 * t414;
  t417 = t16 * t16;
  t418 = my_piecewise3(t10, t417, 1);
  t419 = t418 * t418;
  t422 = -0.70121174589195667679e-1 * t294 + 0.32022742560873636667e-1;
  t427 = log(0.2e1);
  t428 = 0.1e1 - t427;
  t429 = t428 * t350;
  t430 = t419 * t418;
  t431 = -t316 + t331;
  t432 = 0.1e1 / t428;
  t437 = exp(-t431 * t432 * t37 / t430);
  t438 = t437 - 0.1e1;
  t441 = t61 * t422 * t432;
  t443 = 0.1e1 / t438;
  t447 = 0.1e1 / t28 / t79;
  t450 = t37 * t443 * sigma[0] * t447 * t9 * t276;
  t451 = t24 * t415 * t441 * t450;
  t452 = t451 / 0.32e2;
  t453 = 0.1e1 - t452;
  t455 = my_piecewise3(DBL_EPSILON < t453, t453, DBL_EPSILON);
  t456 = POW_1_4(t455);
  t461 = t422 * t422;
  t463 = t428 * t428;
  t467 = t438 * t438;
  t472 = 0.1e1 / t56 / t92;
  t479 = 0.1e1 / (0.1e1 + 0.3e1 / 0.1024e4 * t277 * t414 * t85 * t461 / t463 * t96 / t467 * t190 * t472 * t54 * t4);
  t481 = 0.1e1 - 0.5e1 / 0.64e2 * t451;
  t483 = my_piecewise3(DBL_EPSILON < t481, t481, DBL_EPSILON);
  t487 = 0.1e1 + t438 * (0.1e1 - 0.1e1 / t456) * (0.1e1 - t479 + 0.1e1 / t483);
  t489 = my_piecewise3(DBL_MIN < t487, t487, DBL_MIN);
  t490 = log(t489);
  t493 = 0.1e1 + t452;
  t495 = my_piecewise3(DBL_EPSILON < t493, t493, DBL_EPSILON);
  t496 = POW_1_4(t495);
  t506 = 0.1e1 + (t437 + 0.185e1) * t24 * t415 * t441 * t450 / 0.128e3;
  t508 = my_piecewise3(DBL_EPSILON < t506, t506, DBL_EPSILON);
  t512 = 0.1e1 + t438 * (0.1e1 - 0.1e1 / t496) * (0.1e1 - t479 - 0.1e1 / t508);
  t514 = my_piecewise3(DBL_MIN < t512, t512, DBL_MIN);
  t515 = log(t514);
  t518 = my_piecewise3(0.e0 <= -0.3e1 / 0.16e2 * t277 * t230 * t415 * t61 * t419 * t422, t429 * t430 * t490, t429 * t430 * t515);
  t521 = t243 / 0.3e3;
  t524 = my_piecewise3(t521 < -t46, -t46, t521);
  t526 = exp(-0.1e1 / t524);
  t527 = my_piecewise3(t521 <= -t46, 0, t526);
  tzk1 = t266 + (0.1e1 - t411) * (-t316 + t331 + t518 - t266) * (0.1e1 - t527);

  t532 = 0.1e1 / (0.1e1 + 0.34899999999999999999e0 * t231);
  tzk2 = -0.4918e-1 * t532;

  t535 = exp(-0.2533e0 * t231);
  t536 = t535 * t532;
  t539 = (0.2533e0 + 0.349e0 * t532) * t231;
  tzk3 = -0.649176e-2 * t536 * t242 * (-0.1e1 / 0.72e2 - 0.7e1 / 0.72e2 * t539);

  t546 = p->zeta_threshold * p->zeta_threshold;
  t548 = my_piecewise3(t10, t417 * t546, 1);
  tzk4 = -0.1947528e-2 * t536 * t276 * t60 * t548;

  tzk5 = 0.81147e-3 * t536 * (0.5e1 / 0.2e1 - t539 / 0.18e2) * t242 * t548;

  t561 = my_piecewise3(t10, t417 * t546 * p->zeta_threshold, 1);
  tzk6 = 0.45081666666666666668e-4 * t536 * (t539 - 0.11e2) * t242 * t561;

  t567 = my_piecewise3(t10, t546, 1);
  tzk7 = -0.81147e-3 * t536 * t9 * (0.4e1 / 0.3e1 * t183 * t185 * t548 - t567 * sigma[0] * t54 * t185 * t548 / 0.2e1);

  t578 = t20 * t25;
  t579 = t26 * t28;
  t583 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t8 * t9 * t578 * t579);
  tzk8 = 0.2e1 * t583;

  t585 = 0.3e1 / 0.1e2 * t35 * t60;
  t586 = t585 - t59;
  t588 = t585 + t59;
  t589 = 0.1e1 / t588;
  t594 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t586 * t589);
  tzk9 = 0.2e1 * t594;

  t595 = t586 * t586;
  t597 = t588 * t588;
  t598 = 0.1e1 / t597;
  t603 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t595 * t598);
  tzk10 = 0.2e1 * t603;

  t604 = t595 * t586;
  t606 = t597 * t588;
  t607 = 0.1e1 / t606;
  t612 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t604 * t607);
  tzk11 = 0.2e1 * t612;

  t613 = t595 * t595;
  t615 = t597 * t597;
  t616 = 0.1e1 / t615;
  t621 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t613 * t616);
  tzk12 = 0.2e1 * t621;

  t622 = t613 * t586;
  t625 = 0.1e1 / t615 / t588;
  t630 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t622 * t625);
  tzk13 = 0.2e1 * t630;

  t631 = t4 * t20;
  t635 = 0.1e1 + 0.4e-2 * t198;
  t636 = 0.1e1 / t635;
  t637 = sigma[0] * t636;
  t641 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t631 * t25 * t26 * t447 * t637);
  tzk14 = 0.2e1 * t641;

  t642 = t631 * t27;
  t649 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t642 * t447 * t586 * t589 * sigma[0] * t636);
  tzk15 = 0.2e1 * t649;

  t656 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t642 * t447 * t595 * t598 * sigma[0] * t636);
  tzk16 = 0.2e1 * t656;

  t663 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t642 * t447 * t604 * t607 * sigma[0] * t636);
  tzk17 = 0.2e1 * t663;

  t670 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t642 * t447 * t613 * t616 * sigma[0] * t636);
  tzk18 = 0.2e1 * t670;

  t671 = t4 * t54;
  t672 = t671 * t578;
  t673 = t26 * t94;
  t674 = t635 * t635;
  t675 = 0.1e1 / t674;
  t676 = t190 * t675;
  t680 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t672 * t673 * t676);
  tzk19 = 0.2e1 * t680;

  t681 = t578 * t26;
  t682 = t671 * t681;
  t683 = t94 * t586;
  t689 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t682 * t683 * t589 * t190 * t675);
  tzk20 = 0.2e1 * t689;

  t690 = t94 * t595;
  t696 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t682 * t690 * t598 * t190 * t675);
  tzk21 = 0.2e1 * t696;

  t703 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t682 * t94 * t604 * t607 * t190 * t675);
  tzk22 = 0.2e1 * t703;

  t704 = t4 * t9;
  t708 = 0.1e1 / t56 / t92 / t80;
  t710 = t190 * sigma[0];
  t712 = 0.1e1 / t674 / t635;
  t717 = my_piecewise3(t3, 0, -0.2237731569769975749e-7 * t704 * t578 * t26 * t708 * t710 * t712);
  tzk23 = 0.2e1 * t717;

  t718 = t704 * t681;
  t725 = my_piecewise3(t3, 0, -0.2237731569769975749e-7 * t718 * t708 * t586 * t589 * t710 * t712);
  tzk24 = 0.2e1 * t725;

  t732 = my_piecewise3(t3, 0, -0.2237731569769975749e-7 * t718 * t708 * t595 * t598 * t710 * t712);
  tzk25 = 0.2e1 * t732;

  t735 = POW_1_3(0.1e1 / t14);
  t738 = 0.1e1 + 0.39999999999999999999e0 * t231 * t9 * t735;
  t739 = 0.1e1 / t738;
  t744 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t739);
  tzk26 = 0.2e1 * t744;

  t746 = t8 * t21 * t25;
  t747 = t586 * t589;
  t752 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t747 * t739);
  tzk27 = 0.2e1 * t752;

  t753 = t595 * t598;
  t758 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t753 * t739);
  tzk28 = 0.2e1 * t758;

  t759 = t604 * t607;
  t764 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t759 * t739);
  tzk29 = 0.2e1 * t764;

  t765 = t613 * t616;
  t770 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t765 * t739);
  tzk30 = 0.2e1 * t770;

  t771 = t447 * sigma[0];
  t776 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t642 * t771 * t636 * t739);
  tzk31 = 0.2e1 * t776;

  t778 = t631 * t27 * t447;
  t779 = t637 * t739;
  t783 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t778 * t747 * t779);
  tzk32 = 0.2e1 * t783;

  t787 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t778 * t753 * t779);
  tzk33 = 0.2e1 * t787;

  t791 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t778 * t759 * t779);
  tzk34 = 0.2e1 * t791;

  t792 = t676 * t739;
  t796 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t672 * t673 * t792);
  tzk35 = 0.2e1 * t796;

  t801 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t682 * t683 * t589 * t792);
  tzk36 = 0.2e1 * t801;

  t806 = my_piecewise3(t3, 0, -0.27971644622124696862e-5 * t682 * t690 * t598 * t792);
  tzk37 = 0.2e1 * t806;

  t807 = t738 * t738;
  t808 = 0.1e1 / t807;
  t813 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t808);
  tzk38 = 0.2e1 * t813;

  t818 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t747 * t808);
  tzk39 = 0.2e1 * t818;

  t823 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t753 * t808);
  tzk40 = 0.2e1 * t823;

  t828 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t759 * t808);
  tzk41 = 0.2e1 * t828;

  t833 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t642 * t771 * t636 * t808);
  tzk42 = 0.2e1 * t833;

  t834 = t637 * t808;
  t838 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t778 * t747 * t834);
  tzk43 = 0.2e1 * t838;

  t842 = my_piecewise3(t3, 0, -0.69929111555311742156e-3 * t778 * t753 * t834);
  tzk44 = 0.2e1 * t842;

  t844 = 0.1e1 / t807 / t738;
  t849 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t22 * t27 * t28 * t844);
  tzk45 = 0.2e1 * t849;

  t854 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t747 * t844);
  tzk46 = 0.2e1 * t854;

  t859 = my_piecewise3(t3, 0, -0.3e1 / 0.16e2 * t746 * t579 * t753 * t844);
  tzk47 = 0.2e1 * t859;

  tzk48 = t431;

  tzk49 = t747 * tzk48;

  tzk50 = t753 * tzk48;

  tzk51 = t759 * tzk48;

  tzk52 = t765 * tzk48;

  t860 = t622 * t625;
  tzk53 = t860 * tzk48;

  t864 = t613 * t595 / t615 / t597;
  tzk54 = t864 * tzk48;

  t868 = t613 * t604 / t615 / t606;
  tzk55 = t868 * tzk48;

  t869 = t613 * t613;
  t870 = t615 * t615;
  t872 = t869 / t870;
  tzk56 = t872 * tzk48;

  t879 = t432 * t443;
  t882 = t419 * t419;
  t891 = t771 * t9 / t419 * t276 * t27 / 0.96e2 + 0.21437009059034868485e-3 * t879 * t190 * t472 * t54 / t882 * t4 / t277 * t230;
  t900 = log(0.1e1 + 0.65854491829355115987e0 * t891 * t432 / (0.1e1 + 0.65854491829355115987e0 * t879 * t891));
  tzk57 = t429 * t430 * t900;

  t904 = t350 * t430 * t900;
  tzk58 = t747 * t428 * t904;

  tzk59 = t753 * t428 * t904;

  tzk60 = t759 * t428 * t904;

  tzk61 = t765 * t428 * t904;

  tzk62 = t860 * t428 * t904;

  tzk63 = t864 * t428 * t904;

  tzk64 = t868 * t428 * t904;

  tzk65 = t872 * t428 * t904;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC)) {
    out->zk[ip*p->dim.zk + 0] += tzk0;
    out->zk[ip*p->dim.zk + 1] += tzk1;
    out->zk[ip*p->dim.zk + 2] += tzk2;
    out->zk[ip*p->dim.zk + 3] += tzk3;
    out->zk[ip*p->dim.zk + 4] += tzk4;
    out->zk[ip*p->dim.zk + 5] += tzk5;
    out->zk[ip*p->dim.zk + 6] += tzk6;
    out->zk[ip*p->dim.zk + 7] += tzk7;
    out->zk[ip*p->dim.zk + 8] += tzk8;
    out->zk[ip*p->dim.zk + 9] += tzk9;
    out->zk[ip*p->dim.zk + 10] += tzk10;
    out->zk[ip*p->dim.zk + 11] += tzk11;
    out->zk[ip*p->dim.zk + 12] += tzk12;
    out->zk[ip*p->dim.zk + 13] += tzk13;
    out->zk[ip*p->dim.zk + 14] += tzk14;
    out->zk[ip*p->dim.zk + 15] += tzk15;
    out->zk[ip*p->dim.zk + 16] += tzk16;
    out->zk[ip*p->dim.zk + 17] += tzk17;
    out->zk[ip*p->dim.zk + 18] += tzk18;
    out->zk[ip*p->dim.zk + 19] += tzk19;
    out->zk[ip*p->dim.zk + 20] += tzk20;
    out->zk[ip*p->dim.zk + 21] += tzk21;
    out->zk[ip*p->dim.zk + 22] += tzk22;
    out->zk[ip*p->dim.zk + 23] += tzk23;
    out->zk[ip*p->dim.zk + 24] += tzk24;
    out->zk[ip*p->dim.zk + 25] += tzk25;
    out->zk[ip*p->dim.zk + 26] += tzk26;
    out->zk[ip*p->dim.zk + 27] += tzk27;
    out->zk[ip*p->dim.zk + 28] += tzk28;
    out->zk[ip*p->dim.zk + 29] += tzk29;
    out->zk[ip*p->dim.zk + 30] += tzk30;
    out->zk[ip*p->dim.zk + 31] += tzk31;
    out->zk[ip*p->dim.zk + 32] += tzk32;
    out->zk[ip*p->dim.zk + 33] += tzk33;
    out->zk[ip*p->dim.zk + 34] += tzk34;
    out->zk[ip*p->dim.zk + 35] += tzk35;
    out->zk[ip*p->dim.zk + 36] += tzk36;
    out->zk[ip*p->dim.zk + 37] += tzk37;
    out->zk[ip*p->dim.zk + 38] += tzk38;
    out->zk[ip*p->dim.zk + 39] += tzk39;
    out->zk[ip*p->dim.zk + 40] += tzk40;
    out->zk[ip*p->dim.zk + 41] += tzk41;
    out->zk[ip*p->dim.zk + 42] += tzk42;
    out->zk[ip*p->dim.zk + 43] += tzk43;
    out->zk[ip*p->dim.zk + 44] += tzk44;
    out->zk[ip*p->dim.zk + 45] += tzk45;
    out->zk[ip*p->dim.zk + 46] += tzk46;
    out->zk[ip*p->dim.zk + 47] += tzk47;
    out->zk[ip*p->dim.zk + 48] += tzk48;
    out->zk[ip*p->dim.zk + 49] += tzk49;
    out->zk[ip*p->dim.zk + 50] += tzk50;
    out->zk[ip*p->dim.zk + 51] += tzk51;
    out->zk[ip*p->dim.zk + 52] += tzk52;
    out->zk[ip*p->dim.zk + 53] += tzk53;
    out->zk[ip*p->dim.zk + 54] += tzk54;
    out->zk[ip*p->dim.zk + 55] += tzk55;
    out->zk[ip*p->dim.zk + 56] += tzk56;
    out->zk[ip*p->dim.zk + 57] += tzk57;
    out->zk[ip*p->dim.zk + 58] += tzk58;
    out->zk[ip*p->dim.zk + 59] += tzk59;
    out->zk[ip*p->dim.zk + 60] += tzk60;
    out->zk[ip*p->dim.zk + 61] += tzk61;
    out->zk[ip*p->dim.zk + 62] += tzk62;
    out->zk[ip*p->dim.zk + 63] += tzk63;
    out->zk[ip*p->dim.zk + 64] += tzk64;
    out->zk[ip*p->dim.zk + 65] += tzk65;
  }

}

#endif


#ifndef XC_DONT_COMPILE_EXC
GPU_DEVICE_FUNCTION static inline void
func_exc_pol(const xc_func_type *p, size_t ip, const double *rho, const double *sigma, const double *lapl, const double *tau, xc_mgga_out_params *out)
{ 
  double t2, t3, t5, t6, t10, t11, t12, t13;
  double t15, t16, t17, t18, t19, t20, t21, t22;
  double t23, t25, t26, t27, t29, t30, t31, t32;
  double t33, t34, t35, t36, t37, t38, t39, t40;
  double t44, t45, t46, t47, t49, t51, t53, t54;
  double t55, t58, t60, t61, t62, t63, t66, t67;
  double t68, t69, t74, t78, t80, t81, t84, t85;
  double t86, t91, t92, t93, t97, t98, t99, t102;
  double t103, t104, t108, t115, t116, t121, t125, t128;
  double t137, t138, t150, t155, t163, t164, t170, t171;
  double t175, t180, t183, t186, t187, t188, t189, t190;
  double t192, t193, t195, t200, t203, t205, t206, t211;
  double t214, t216, t217, t225, t229, t230, t231, t233;
  double t235, t236, t237, t238, t239, t244, t246, t249;
  double t251, t252, t253, t254, t257, t262, t266, t268;
  double t269, t272, t273, t274, t278, t282, t283, t284;
  double t287, t291, t296, t301, t326, t331, t337, t338;
  double t342, t347, t350, t353, t354, t355, t356, t357;
  double t359, t360, t362, t367, t370, t372, t373, t378;
  double t381, t383, t384, t392, tzk0, t394, t395, t397;
  double t400, t401, t403, t407, t408, t409, t412, t413;
  double t416, t420, t422, t423, t426, t427, t429, t430;
  double t432, t433, t436, t441, t442, t443, t445, t446;
  double t451, t452, t453, t454, t455, t456, t457, t458;
  double t459, t460, t461, t468, t469, t471, t472, t473;
  double t474, t475, t477, t480, t485, t490, t495, t496;
  double t497, t500, t504, t510, t512, t513, t514, t528;
  double t529, t532, t534, t536, t539, t541, t543, t545;
  double t548, t550, t551, t552, t556, t557, t561, t562;
  double t572, t575, t578, t582, t584, t585, t589, t590;
  double t594, t604, t607, t610, t611, t615, t626, t632;
  double t634, t636, t637, t639, t640, t641, t642, t644;
  double t649, t650, t651, t652, t653, t654, t655, t657;
  double t658, t659, t660, t661, t666, t667, t673, t677;
  double t680, t682, t683, t684, t685, t687, t688, t694;
  double t695, t697, t701, t704, t707, t708, t710, t711;
  double t718, t720, t722, t726, t728, t729, t732, t734;
  double t735, t747, t749, t753, t755, t756, t759, t762;
  double t765, t767, t768, tzk1, t773, t776, tzk2, t780;
  double t781, t784, tzk3, t795, t796, t797, t799, t800;
  double t802, tzk4, t807, t811, t812, tzk5, t819, t822;
  double t826, tzk6, t833, t838, tzk7, t847, t848, t849;
  double t853, t854, t858, tzk8, t860, t861, t863, t864;
  double t865, t869, t870, t872, t873, t874, t878, tzk9;
  double t879, t881, t882, t883, t887, t888, t890, t891;
  double t892, t896, tzk10, t897, t900, t901, t905, t906;
  double t909, t910, t914, tzk11, t915, t917, t918, t919;
  double t923, t924, t926, t927, t928, t932, tzk12, t941;
  double t950, tzk13, t951, t952, t954, t955, t956, t960;
  double t961, t963, t964, t965, t969, tzk14, t971, t975;
  double t977, t981, tzk15, t985, t989, tzk16, t993, t997;
  double tzk17, t1001, t1005, tzk18, t1006, t1007, t1008, t1012;
  double t1013, t1014, t1015, t1019, tzk19, t1023, t1027, tzk20;
  double t1031, t1035, tzk21, t1039, t1043, tzk22, t1049, t1053;
  double t1059, t1063, tzk23, t1067, t1071, tzk24, t1075, t1079;
  double tzk25, t1080, t1082, t1085, t1086, t1091, t1093, t1096;
  double t1097, t1102, tzk26, t1104, t1105, t1110, t1112, t1113;
  double t1118, tzk27, t1119, t1124, t1125, t1130, tzk28, t1131;
  double t1136, t1137, t1142, tzk29, t1148, t1154, tzk30, t1155;
  double t1156, t1157, t1161, t1162, t1163, t1164, t1168, tzk31;
  double t1170, t1171, t1172, t1176, t1178, t1179, t1183, tzk32;
  double t1184, t1188, t1189, t1193, tzk33, t1198, t1203, tzk34;
  double t1206, t1210, t1213, t1217, tzk35, t1222, t1227, tzk36;
  double t1232, t1237, tzk37, t1238, t1239, t1244, t1245, t1246;
  double t1251, tzk38, t1256, t1261, tzk39, t1266, t1271, tzk40;
  double t1276, t1281, tzk41, t1282, t1286, t1287, t1291, tzk42;
  double t1295, t1299, tzk43, t1303, t1307, tzk44, t1309, t1314;
  double t1316, t1321, tzk45, t1326, t1331, tzk46, t1336, t1341;
  double tzk47, tzk48, t1343, t1344, t1345, t1347, tzk49, t1348;
  double t1349, t1351, tzk50, t1352, t1353, t1355, tzk51, t1356;
  double t1357, t1359, tzk52, t1363, tzk53, t1367, tzk54, t1371;
  double tzk55, t1372, t1373, t1375, tzk56, t1381, t1391, t1400;
  double tzk57, t1404, tzk58, tzk59, tzk60, tzk61, tzk62, tzk63;
  double tzk64, tzk65;

  t2 = rho[0] - rho[1];
  t3 = rho[0] + rho[1];
  t5 = t2 / t3;
  t6 = 0.1e1 + t5;
  t10 = t6 * t3 / 0.2e1 <= p->dens_threshold;
  t11 = M_CBRT3;
  t12 = M_CBRTPI;
  t13 = t12 * t12;
  t15 = t11 / t13;
  t16 = M_CBRT2;
  t17 = t6 <= p->zeta_threshold;
  t18 = p->zeta_threshold - 0.1e1;
  t19 = 0.1e1 - t5;
  t20 = t19 <= p->zeta_threshold;
  t21 = -t18;
  t22 = my_piecewise5(t17, t18, t20, t21, t5);
  t23 = 0.1e1 + t22;
  t25 = POW_1_3(p->zeta_threshold);
  t26 = t25 * p->zeta_threshold;
  t27 = POW_1_3(t23);
  t29 = my_piecewise3(t23 <= p->zeta_threshold, t26, t27 * t23);
  t30 = t16 * t29;
  t31 = t15 * t30;
  t32 = 0.1e1 / M_PI;
  t33 = POW_1_3(t32);
  t34 = 0.1e1 / t33;
  t35 = M_CBRT4;
  t36 = t34 * t35;
  t37 = POW_1_3(t3);
  t38 = sqrt(0.3e1);
  t39 = sqrt(sigma[0]);
  t40 = POW_1_3(rho[0]);
  t44 = M_CBRT6;
  t45 = t44 * t44;
  t46 = M_PI * M_PI;
  t47 = POW_1_3(t46);
  t49 = t45 / t47;
  t51 = sqrt(t39 / t40 / rho[0] * t49);
  t53 = 0.33684323989301858702e-1 * t38 * t51;
  t54 = log(DBL_EPSILON);
  t55 = 0.1e1 / t54;
  t58 = my_piecewise3(t53 < -t55, -t55, t53);
  t60 = exp(-0.1e1 / t58);
  t61 = my_piecewise3(t53 <= -t55, 0, t60);
  t62 = 0.1174e1 * t61;
  t63 = t40 * t40;
  t66 = tau[0] / t63 / rho[0];
  t67 = t47 * t47;
  t68 = 0.1e1 / t67;
  t69 = t44 * t68;
  t74 = sigma[0] / rho[0] / tau[0] / 0.8e1;
  t78 = my_piecewise3(0.e0 < 0.9999999999e0 - t74, 0.1e1 - t74, 0.1e-9);
  t80 = t66 * t69 * t78;
  t81 = 0.5e1 / 0.9e1 * t80;
  t84 = tau[0] * tau[0];
  t85 = rho[0] * rho[0];
  t86 = t85 * rho[0];
  t91 = 0.1e1 / t47 / t46;
  t92 = t45 * t91;
  t93 = t78 * t78;
  t97 = t84 * tau[0];
  t98 = t85 * t85;
  t99 = t98 * rho[0];
  t102 = t46 * t46;
  t103 = 0.1e1 / t102;
  t104 = t93 * t78;
  t108 = t84 * t84;
  t115 = t44 / t67 / t102;
  t116 = t93 * t93;
  t121 = t98 * t98;
  t125 = t102 * t46;
  t128 = t45 / t47 / t125;
  t137 = t102 * t102;
  t138 = 0.1e1 / t137;
  t150 = t44 / t67 / t137;
  t155 = t108 * t108;
  t163 = t45 / t47 / t137 / t46;
  t164 = t116 * t116;
  t170 = my_piecewise3(DBL_EPSILON < t81, t81, DBL_EPSILON);
  t171 = t170 - 0.1e1;
  t175 = t171 * t171;
  t180 = atan(M_PI * (-0.12063067191025636561e1 * t171 / t170 - 0.11103356059345265253e1 * t175) / 0.2e1);
  t183 = my_piecewise3(t81 <= DBL_EPSILON, 0.99999999999999999996e0 - 0.18665085944258768548e0 * t80 - 0.19914010358223149895e0 * t84 / t40 / t86 * t92 * t93 - 0.60639971965846678506e0 * t97 / t99 * t103 * t104 - 0.76375207387723991158e-1 * t108 / t63 / t98 / t85 * t115 * t116 + 0.14594008525673758611e0 * t108 * tau[0] / t40 / t121 * t128 * t116 * t78 + 0.87379127649768217944e0 * t108 * t84 / t121 / t85 * t138 * t116 * t93 + 0.40664104271070689002e0 * t108 * t97 / t63 / t121 / t86 * t150 * t116 * t104 - 0.44134118356287103732e-3 * t155 / t40 / t121 / t99 * t163 * t164, 0.2e1 * t32 * t180);
  t186 = 0.1e1 / t63 / t85;
  t187 = sigma[0] * t186;
  t188 = t187 * t69;
  t189 = 0.13342809400364015279e-2 * t188;
  t190 = sigma[0] * sigma[0];
  t192 = 0.1e1 / t40 / t99;
  t193 = t190 * t192;
  t195 = 0.15398708928290202559e-3 * t193 * t92;
  t200 = 0.34435261707988980717e-1 * t187 * t69 * (0.1e1 + t188 / 0.24e2);
  t203 = my_piecewise3(t200 < -t55, -t55, t200);
  t205 = exp(-0.1e1 / t203);
  t206 = my_piecewise3(t200 <= -t55, 0, t205);
  t211 = t188 / 0.6e3;
  t214 = my_piecewise3(t211 < -t55, -t55, t211);
  t216 = exp(-0.1e1 / t214);
  t217 = my_piecewise3(t211 <= -t55, 0, t216);
  t225 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t37 * (0.1174e1 - t62 + (0.1e1 - t183) * (-0.174e0 - t189 - t195 + t62 + t206 * (0.1e0 + t189 + t195 - t62)) * (0.1e1 - t217)));
  t229 = t19 * t3 / 0.2e1 <= p->dens_threshold;
  t230 = my_piecewise5(t20, t18, t17, t21, -t5);
  t231 = 0.1e1 + t230;
  t233 = POW_1_3(t231);
  t235 = my_piecewise3(t231 <= p->zeta_threshold, t26, t233 * t231);
  t236 = t16 * t235;
  t237 = t15 * t236;
  t238 = sqrt(sigma[2]);
  t239 = POW_1_3(rho[1]);
  t244 = sqrt(t238 / t239 / rho[1] * t49);
  t246 = 0.33684323989301858702e-1 * t38 * t244;
  t249 = my_piecewise3(t246 < -t55, -t55, t246);
  t251 = exp(-0.1e1 / t249);
  t252 = my_piecewise3(t246 <= -t55, 0, t251);
  t253 = 0.1174e1 * t252;
  t254 = t239 * t239;
  t257 = tau[1] / t254 / rho[1];
  t262 = sigma[2] / rho[1] / tau[1] / 0.8e1;
  t266 = my_piecewise3(0.e0 < 0.9999999999e0 - t262, 0.1e1 - t262, 0.1e-9);
  t268 = t257 * t69 * t266;
  t269 = 0.5e1 / 0.9e1 * t268;
  t272 = tau[1] * tau[1];
  t273 = rho[1] * rho[1];
  t274 = t273 * rho[1];
  t278 = t266 * t266;
  t282 = t272 * tau[1];
  t283 = t273 * t273;
  t284 = t283 * rho[1];
  t287 = t278 * t266;
  t291 = t272 * t272;
  t296 = t278 * t278;
  t301 = t283 * t283;
  t326 = t291 * t291;
  t331 = t296 * t296;
  t337 = my_piecewise3(DBL_EPSILON < t269, t269, DBL_EPSILON);
  t338 = t337 - 0.1e1;
  t342 = t338 * t338;
  t347 = atan(M_PI * (-0.12063067191025636561e1 * t338 / t337 - 0.11103356059345265253e1 * t342) / 0.2e1);
  t350 = my_piecewise3(t269 <= DBL_EPSILON, 0.99999999999999999996e0 - 0.18665085944258768548e0 * t268 - 0.19914010358223149895e0 * t272 / t239 / t274 * t92 * t278 - 0.60639971965846678506e0 * t282 / t284 * t103 * t287 - 0.76375207387723991158e-1 * t291 / t254 / t283 / t273 * t115 * t296 + 0.14594008525673758611e0 * t291 * tau[1] / t239 / t301 * t128 * t296 * t266 + 0.87379127649768217944e0 * t291 * t272 / t301 / t273 * t138 * t296 * t278 + 0.40664104271070689002e0 * t291 * t282 / t254 / t301 / t274 * t150 * t296 * t287 - 0.44134118356287103732e-3 * t326 / t239 / t301 / t284 * t163 * t331, 0.2e1 * t32 * t347);
  t353 = 0.1e1 / t254 / t273;
  t354 = sigma[2] * t353;
  t355 = t354 * t69;
  t356 = 0.13342809400364015279e-2 * t355;
  t357 = sigma[2] * sigma[2];
  t359 = 0.1e1 / t239 / t284;
  t360 = t357 * t359;
  t362 = 0.15398708928290202559e-3 * t360 * t92;
  t367 = 0.34435261707988980717e-1 * t354 * t69 * (0.1e1 + t355 / 0.24e2);
  t370 = my_piecewise3(t367 < -t55, -t55, t367);
  t372 = exp(-0.1e1 / t370);
  t373 = my_piecewise3(t367 <= -t55, 0, t372);
  t378 = t355 / 0.6e3;
  t381 = my_piecewise3(t378 < -t55, -t55, t378);
  t383 = exp(-0.1e1 / t381);
  t384 = my_piecewise3(t378 <= -t55, 0, t383);
  t392 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t37 * (0.1174e1 - t253 + (0.1e1 - t350) * (-0.174e0 - t356 - t362 + t253 + t373 * (0.1e0 + t356 + t362 - t253)) * (0.1e1 - t384)));
  tzk0 = t225 + t392;

  t394 = t35 * t35;
  t395 = 0.1e1 / t37;
  t397 = t11 * t33 * t394 * t395;
  t400 = 0.1e1 / (0.1e1 + 0.5140025e-1 * t397);
  t401 = 0.468e-1 * t400;
  t403 = exp(0.1e1 * t400);
  t407 = sigma[0] + 0.2e1 * sigma[1] + sigma[2];
  t408 = t3 * t3;
  t409 = t37 * t37;
  t412 = t407 / t409 / t408;
  t413 = t11 * t68 * t412;
  t416 = POW_1_4(0.1e1 + 0.51781333333333333332e0 * t413);
  t420 = 0.1e1 + (t403 - 0.1e1) * (0.1e1 - 0.1e1 / t416);
  t422 = my_piecewise3(t420 < DBL_MIN, DBL_MIN, t420);
  t423 = log(t422);
  t426 = t16 - 0.1e1;
  t427 = POW_1_3(t6);
  t429 = my_piecewise3(t17, t26, t427 * t6);
  t430 = POW_1_3(t19);
  t432 = my_piecewise3(t20, t26, t430 * t19);
  t433 = t429 + t432 - 0.2e1;
  t436 = 0.1e1 / t426 / 0.2e1;
  t441 = t2 * t2;
  t442 = t441 * t441;
  t443 = t442 * t442;
  t445 = t408 * t408;
  t446 = t445 * t445;
  t451 = (-t401 + 0.468e-1 * t423) * (0.1e1 - 0.23631e1 * t426 * t433 * t436) * (-t443 * t442 / t446 / t445 + 0.1e1);
  t452 = t6 / 0.2e1;
  t453 = POW_1_3(t452);
  t454 = t453 * t453;
  t455 = t454 * t452;
  t456 = t66 * t455;
  t457 = t19 / 0.2e1;
  t458 = POW_1_3(t457);
  t459 = t458 * t458;
  t460 = t459 * t457;
  t461 = t257 * t460;
  t468 = (t456 + t461 - t412 / 0.8e1) * t44 * t68 / (t455 + t460);
  t469 = 0.5e1 / 0.9e1 * t468;
  t471 = 0.1e1 / DBL_EPSILON;
  t472 = t11 * t11;
  t473 = t33 * t33;
  t474 = t472 * t473;
  t475 = t474 * t394;
  t477 = pow(t397, 0.65e0);
  t480 = pow(t397, 0.9e0);
  t485 = pow(t397, 0.12e1);
  t490 = t11 * t47 * (0.1e1 + 0.4061261981781177613e-1 * t477) / (0.1e1 + 0.1866634826870181886e-1 * t480) / (0.1e1 + 0.56839371244139928087e-2 * t485);
  t495 = sqrt(0.4e1);
  t496 = sqrt(t397);
  t497 = t495 * t496;
  t500 = POW_3_2(t397);
  t504 = t474 * t35 / t409;
  t510 = log(0.1e1 + 0.16081979498692535067e2 / (0.1898925e1 * t497 + 0.8969e0 * t397 + 0.204775e0 * t500 + 0.123235e0 * t504));
  t512 = 0.621814e-1 * (0.1e1 + 0.53425e-1 * t397) * t510;
  t513 = 0.1e1 <= p->zeta_threshold;
  t514 = my_piecewise3(t513, t26, 1);
  t528 = log(0.1e1 + 0.29608749977793437516e2 / (0.258925e1 * t497 + 0.905775e0 * t397 + 0.1100325e0 * t500 + 0.1241775e0 * t504));
  t529 = (0.1e1 + 0.278125e-1 * t397) * t528;
  t532 = -t512 + 0.19751673498613801407e-1 * (0.2e1 * t514 - 0.2e1) * t436 * t529 + t401;
  t534 = my_piecewise3(-DBL_EPSILON < t532, -DBL_EPSILON, t532);
  t536 = (-0.36576794167600310304e-1 * t490 + 0.20989736912384607617e0) / t534;
  t539 = 0.5e1 / 0.36e2 * t397 * t468;
  t541 = my_piecewise3(DBL_EPSILON < t539, t539, DBL_EPSILON);
  t543 = (t469 - 0.1e1) / t541;
  t545 = my_piecewise3(0.e0 <= t543, t543, -t543);
  t548 = 0.3e1 / 0.16e2 * t475 * t536 * t545;
  t550 = 0.1e1 / t46;
  t551 = t471 < t548;
  t552 = my_piecewise3(t551, t548, t471);
  t556 = t552 * t552;
  t557 = t556 * t552;
  t561 = 0.1e1 / t125;
  t562 = t556 * t556;
  t572 = my_piecewise3(t551, t471, t548);
  t575 = atan(M_PI * t572 / 0.2e1);
  t578 = my_piecewise3(t471 <= t548, 0.1e1 - 0.4e1 * t550 / t552 + 0.16e2 / 0.3e1 * t103 / t557 - 0.64e2 / 0.5e1 * t561 / t562 / t552 + 0.256e3 / 0.7e1 * t138 / t562 / t557, 0.2e1 * t32 * t575);
  t582 = 0.3e1 / 0.16e2 * t475 * t536 * t543;
  t584 = t471 < t582;
  t585 = my_piecewise3(t584, t582, t471);
  t589 = t585 * t585;
  t590 = t589 * t585;
  t594 = t589 * t589;
  t604 = my_piecewise3(t584, t471, t582);
  t607 = atan(M_PI * t604 / 0.2e1);
  t610 = my_piecewise3(t471 <= t582, 0.1e1 - 0.4e1 * t550 / t585 + 0.16e2 / 0.3e1 * t103 / t590 - 0.64e2 / 0.5e1 * t561 / t594 / t585 + 0.256e3 / 0.7e1 * t138 / t594 / t590, 0.2e1 * t32 * t607);
  t611 = my_piecewise3(t469 < 0.e0, 0.2e1 + t578, t610);
  t615 = t433 * t436;
  t626 = log(0.1e1 + 0.32163958997385070134e2 / (0.3529725e1 * t497 + 0.1549425e1 * t397 + 0.420775e0 * t500 + 0.1562925e0 * t504));
  t632 = t442 / t445 * t615 * (-0.310907e-1 * (0.1e1 + 0.5137e-1 * t397) * t626 + t512 - 0.19751673498613801407e-1 * t529);
  t634 = 0.19751673498613801407e-1 * t615 * t529;
  t636 = POW_1_3(0.16e2);
  t637 = t636 * t636;
  t639 = t25 * t25;
  t640 = my_piecewise3(t513, t639, 1);
  t641 = t640 * t640;
  t642 = t68 * t641;
  t644 = -0.70121174589195667679e-1 * t490 + 0.32022742560873636667e-1;
  t649 = log(0.2e1);
  t650 = 0.1e1 - t649;
  t651 = t650 * t550;
  t652 = t427 * t427;
  t653 = my_piecewise3(t17, t639, t652);
  t654 = t430 * t430;
  t655 = my_piecewise3(t20, t639, t654);
  t657 = t653 / 0.2e1 + t655 / 0.2e1;
  t658 = t657 * t657;
  t659 = t658 * t657;
  t660 = -t512 + t632 + t634;
  t661 = 0.1e1 / t650;
  t666 = exp(-t660 * t661 * t46 / t659);
  t667 = t666 - 0.1e1;
  t673 = 0.1e1 / t667;
  t677 = 0.1e1 / t37 / t408;
  t680 = t472 / t658;
  t682 = t46 * t673 * t407 * t677 * t16 * t680;
  t683 = t33 * t637 * t68 * t641 * t644 * t661 * t682;
  t684 = t683 / 0.32e2;
  t685 = 0.1e1 - t684;
  t687 = my_piecewise3(DBL_EPSILON < t685, t685, DBL_EPSILON);
  t688 = POW_1_4(t687);
  t694 = t641 * t641;
  t695 = t644 * t644;
  t697 = t650 * t650;
  t701 = t667 * t667;
  t704 = t407 * t407;
  t707 = 0.1e1 / t409 / t445;
  t708 = t16 * t16;
  t710 = t658 * t658;
  t711 = 0.1e1 / t710;
  t718 = 0.1e1 / (0.1e1 + 0.3e1 / 0.1024e4 * t473 * t636 * t91 * t694 * t695 / t697 * t102 / t701 * t704 * t707 * t708 * t711 * t11);
  t720 = 0.1e1 - 0.5e1 / 0.64e2 * t683;
  t722 = my_piecewise3(DBL_EPSILON < t720, t720, DBL_EPSILON);
  t726 = 0.1e1 + t667 * (0.1e1 - 0.1e1 / t688) * (0.1e1 - t718 + 0.1e1 / t722);
  t728 = my_piecewise3(DBL_MIN < t726, t726, DBL_MIN);
  t729 = log(t728);
  t732 = 0.1e1 + t684;
  t734 = my_piecewise3(DBL_EPSILON < t732, t732, DBL_EPSILON);
  t735 = POW_1_4(t734);
  t747 = 0.1e1 + (t666 + 0.185e1) * t33 * t637 * t642 * t644 * t661 * t682 / 0.128e3;
  t749 = my_piecewise3(DBL_EPSILON < t747, t747, DBL_EPSILON);
  t753 = 0.1e1 + t667 * (0.1e1 - 0.1e1 / t735) * (0.1e1 - t718 - 0.1e1 / t749);
  t755 = my_piecewise3(DBL_MIN < t753, t753, DBL_MIN);
  t756 = log(t755);
  t759 = my_piecewise3(0.e0 <= -0.3e1 / 0.16e2 * t473 * t394 * t637 * t642 * t644, t651 * t659 * t729, t651 * t659 * t756);
  t762 = t413 / 0.3e3;
  t765 = my_piecewise3(t762 < -t55, -t55, t762);
  t767 = exp(-0.1e1 / t765);
  t768 = my_piecewise3(t762 <= -t55, 0, t767);
  tzk1 = t451 + (0.1e1 - t611) * (-t512 + t632 + t634 + t759 - t451) * (0.1e1 - t768);

  t773 = 0.1e1 - t441 / t408;
  t776 = 0.1e1 / (0.1e1 + 0.34899999999999999999e0 * t395);
  tzk2 = -0.4918e-1 * t773 * t776;

  t780 = exp(-0.2533e0 * t395);
  t781 = t780 * t776;
  t784 = (0.2533e0 + 0.349e0 * t776) * t395;
  tzk3 = -0.649176e-2 * t781 * t412 * (t773 * (0.47e2 - 0.7e1 * t784) / 0.72e2 - 0.2e1 / 0.3e1);

  t795 = p->zeta_threshold * p->zeta_threshold;
  t796 = t639 * t795;
  t797 = t6 * t6;
  t799 = my_piecewise3(t17, t796, t652 * t797);
  t800 = t19 * t19;
  t802 = my_piecewise3(t20, t796, t654 * t800);
  tzk4 = -0.973764e-3 * t781 * t472 * t67 * t773 * (t799 + t802);

  t807 = t781 * t16;
  t811 = t187 * t799;
  t812 = t354 * t802;
  tzk5 = 0.2028675e-3 * t807 * t773 * (0.5e1 / 0.2e1 - t784 / 0.18e2) * (t811 + t812);

  t819 = t639 * t795 * p->zeta_threshold;
  t822 = my_piecewise3(t17, t819, t652 * t797 * t6);
  t826 = my_piecewise3(t20, t819, t654 * t800 * t19);
  tzk6 = 0.11270416666666666667e-4 * t807 * t773 * (t784 - 0.11e2) * (t187 * t822 + t354 * t826);

  t833 = my_piecewise3(t17, t795, t797);
  t838 = my_piecewise3(t20, t795, t800);
  tzk7 = -0.81147e-3 * t781 * t16 * (0.2e1 / 0.3e1 * t811 + 0.2e1 / 0.3e1 * t812 - t833 * sigma[2] * t353 * t802 / 0.4e1 - t838 * sigma[0] * t186 * t799 / 0.4e1);

  t847 = t15 * t16;
  t848 = t29 * t34;
  t849 = t35 * t37;
  t853 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t847 * t848 * t849);
  t854 = t235 * t34;
  t858 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t847 * t854 * t849);
  tzk8 = t853 + t858;

  t860 = 0.3e1 / 0.1e2 * t45 * t67;
  t861 = t860 - t66;
  t863 = t860 + t66;
  t864 = 0.1e1 / t863;
  t865 = t37 * t861 * t864;
  t869 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t865);
  t870 = t860 - t257;
  t872 = t860 + t257;
  t873 = 0.1e1 / t872;
  t874 = t37 * t870 * t873;
  t878 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t874);
  tzk9 = t869 + t878;

  t879 = t861 * t861;
  t881 = t863 * t863;
  t882 = 0.1e1 / t881;
  t883 = t37 * t879 * t882;
  t887 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t883);
  t888 = t870 * t870;
  t890 = t872 * t872;
  t891 = 0.1e1 / t890;
  t892 = t37 * t888 * t891;
  t896 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t892);
  tzk10 = t887 + t896;

  t897 = t879 * t861;
  t900 = 0.1e1 / t881 / t863;
  t901 = t37 * t897 * t900;
  t905 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t901);
  t906 = t888 * t870;
  t909 = 0.1e1 / t890 / t872;
  t910 = t37 * t906 * t909;
  t914 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t910);
  tzk11 = t905 + t914;

  t915 = t879 * t879;
  t917 = t881 * t881;
  t918 = 0.1e1 / t917;
  t919 = t37 * t915 * t918;
  t923 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t919);
  t924 = t888 * t888;
  t926 = t890 * t890;
  t927 = 0.1e1 / t926;
  t928 = t37 * t924 * t927;
  t932 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t928);
  tzk12 = t923 + t932;

  t941 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t37 * t915 * t861 / t917 / t863);
  t950 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t37 * t924 * t870 / t926 / t872);
  tzk13 = t941 + t950;

  t951 = t11 * t16;
  t952 = t951 * t848;
  t954 = 0.1e1 + 0.4e-2 * t187;
  t955 = 0.1e1 / t954;
  t956 = t187 * t955;
  t960 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t952 * t849 * t956);
  t961 = t951 * t854;
  t963 = 0.1e1 + 0.4e-2 * t354;
  t964 = 0.1e1 / t963;
  t965 = t354 * t964;
  t969 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t961 * t849 * t965);
  tzk14 = t960 + t969;

  t971 = t951 * t848 * t35;
  t975 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t971 * t865 * t956);
  t977 = t951 * t854 * t35;
  t981 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t977 * t874 * t965);
  tzk15 = t975 + t981;

  t985 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t971 * t883 * t956);
  t989 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t977 * t892 * t965);
  tzk16 = t985 + t989;

  t993 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t971 * t901 * t956);
  t997 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t977 * t910 * t965);
  tzk17 = t993 + t997;

  t1001 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t971 * t919 * t956);
  t1005 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t977 * t928 * t965);
  tzk18 = t1001 + t1005;

  t1006 = t954 * t954;
  t1007 = 0.1e1 / t1006;
  t1008 = t193 * t1007;
  t1012 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t952 * t849 * t1008);
  t1013 = t963 * t963;
  t1014 = 0.1e1 / t1013;
  t1015 = t360 * t1014;
  t1019 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t961 * t849 * t1015);
  tzk19 = t1012 + t1019;

  t1023 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t971 * t865 * t1008);
  t1027 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t977 * t874 * t1015);
  tzk20 = t1023 + t1027;

  t1031 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t971 * t883 * t1008);
  t1035 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t977 * t892 * t1015);
  tzk21 = t1031 + t1035;

  t1039 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t971 * t901 * t1008);
  t1043 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t977 * t910 * t1015);
  tzk22 = t1039 + t1043;

  t1049 = t190 * sigma[0] / t121 / t1006 / t954;
  t1053 = my_piecewise3(t10, 0, -0.55943289244249393726e-8 * t952 * t849 * t1049);
  t1059 = t357 * sigma[2] / t301 / t1013 / t963;
  t1063 = my_piecewise3(t229, 0, -0.55943289244249393726e-8 * t961 * t849 * t1059);
  tzk23 = t1053 + t1063;

  t1067 = my_piecewise3(t10, 0, -0.55943289244249393726e-8 * t971 * t865 * t1049);
  t1071 = my_piecewise3(t229, 0, -0.55943289244249393726e-8 * t977 * t874 * t1059);
  tzk24 = t1067 + t1071;

  t1075 = my_piecewise3(t10, 0, -0.55943289244249393726e-8 * t971 * t883 * t1049);
  t1079 = my_piecewise3(t229, 0, -0.55943289244249393726e-8 * t977 * t892 * t1059);
  tzk25 = t1075 + t1079;

  t1080 = t395 * t16;
  t1082 = POW_1_3(0.1e1 / t23);
  t1085 = 0.1e1 + 0.39999999999999999999e0 * t1080 * t1082;
  t1086 = 0.1e1 / t1085;
  t1091 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t37 * t1086);
  t1093 = POW_1_3(0.1e1 / t231);
  t1096 = 0.1e1 + 0.39999999999999999999e0 * t1080 * t1093;
  t1097 = 0.1e1 / t1096;
  t1102 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t37 * t1097);
  tzk26 = t1091 + t1102;

  t1104 = t15 * t30 * t34;
  t1105 = t861 * t864;
  t1110 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1105 * t1086);
  t1112 = t15 * t236 * t34;
  t1113 = t870 * t873;
  t1118 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1113 * t1097);
  tzk27 = t1110 + t1118;

  t1119 = t879 * t882;
  t1124 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1119 * t1086);
  t1125 = t888 * t891;
  t1130 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1125 * t1097);
  tzk28 = t1124 + t1130;

  t1131 = t897 * t900;
  t1136 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1131 * t1086);
  t1137 = t906 * t909;
  t1142 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1137 * t1097);
  tzk29 = t1136 + t1142;

  t1148 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t915 * t918 * t1086);
  t1154 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t924 * t927 * t1097);
  tzk30 = t1148 + t1154;

  t1155 = t37 * sigma[0];
  t1156 = t186 * t955;
  t1157 = t1156 * t1086;
  t1161 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t971 * t1155 * t1157);
  t1162 = t37 * sigma[2];
  t1163 = t353 * t964;
  t1164 = t1163 * t1097;
  t1168 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t977 * t1162 * t1164);
  tzk31 = t1161 + t1168;

  t1170 = t36 * t37;
  t1171 = t951 * t29 * t1170;
  t1172 = t1105 * sigma[0];
  t1176 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t1171 * t1172 * t1157);
  t1178 = t951 * t235 * t1170;
  t1179 = t1113 * sigma[2];
  t1183 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t1178 * t1179 * t1164);
  tzk32 = t1176 + t1183;

  t1184 = t1119 * sigma[0];
  t1188 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t1171 * t1184 * t1157);
  t1189 = t1125 * sigma[2];
  t1193 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t1178 * t1189 * t1164);
  tzk33 = t1188 + t1193;

  t1198 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t1171 * t1131 * sigma[0] * t1157);
  t1203 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t1178 * t1137 * sigma[2] * t1164);
  tzk34 = t1198 + t1203;

  t1206 = t192 * t1007 * t1086;
  t1210 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t971 * t37 * t190 * t1206);
  t1213 = t359 * t1014 * t1097;
  t1217 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t977 * t37 * t357 * t1213);
  tzk35 = t1210 + t1217;

  t1222 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t1171 * t1105 * t190 * t1206);
  t1227 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t1178 * t1113 * t357 * t1213);
  tzk36 = t1222 + t1227;

  t1232 = my_piecewise3(t10, 0, -0.13985822311062348431e-5 * t1171 * t1119 * t190 * t1206);
  t1237 = my_piecewise3(t229, 0, -0.13985822311062348431e-5 * t1178 * t1125 * t357 * t1213);
  tzk37 = t1232 + t1237;

  t1238 = t1085 * t1085;
  t1239 = 0.1e1 / t1238;
  t1244 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t37 * t1239);
  t1245 = t1096 * t1096;
  t1246 = 0.1e1 / t1245;
  t1251 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t37 * t1246);
  tzk38 = t1244 + t1251;

  t1256 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1105 * t1239);
  t1261 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1113 * t1246);
  tzk39 = t1256 + t1261;

  t1266 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1119 * t1239);
  t1271 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1125 * t1246);
  tzk40 = t1266 + t1271;

  t1276 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1131 * t1239);
  t1281 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1137 * t1246);
  tzk41 = t1276 + t1281;

  t1282 = t1156 * t1239;
  t1286 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t971 * t1155 * t1282);
  t1287 = t1163 * t1246;
  t1291 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t977 * t1162 * t1287);
  tzk42 = t1286 + t1291;

  t1295 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t1171 * t1172 * t1282);
  t1299 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t1178 * t1179 * t1287);
  tzk43 = t1295 + t1299;

  t1303 = my_piecewise3(t10, 0, -0.34964555777655871078e-3 * t1171 * t1184 * t1282);
  t1307 = my_piecewise3(t229, 0, -0.34964555777655871078e-3 * t1178 * t1189 * t1287);
  tzk44 = t1303 + t1307;

  t1309 = 0.1e1 / t1238 / t1085;
  t1314 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t31 * t36 * t37 * t1309);
  t1316 = 0.1e1 / t1245 / t1096;
  t1321 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t237 * t36 * t37 * t1316);
  tzk45 = t1314 + t1321;

  t1326 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1105 * t1309);
  t1331 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1113 * t1316);
  tzk46 = t1326 + t1331;

  t1336 = my_piecewise3(t10, 0, -0.3e1 / 0.16e2 * t1104 * t849 * t1119 * t1309);
  t1341 = my_piecewise3(t229, 0, -0.3e1 / 0.16e2 * t1112 * t849 * t1125 * t1316);
  tzk47 = t1336 + t1341;

  tzk48 = t660;

  t1343 = t708 * (t456 + t461);
  t1344 = t860 - t1343;
  t1345 = t860 + t1343;
  t1347 = t1344 / t1345;
  tzk49 = t1347 * tzk48;

  t1348 = t1344 * t1344;
  t1349 = t1345 * t1345;
  t1351 = t1348 / t1349;
  tzk50 = t1351 * tzk48;

  t1352 = t1348 * t1344;
  t1353 = t1349 * t1345;
  t1355 = t1352 / t1353;
  tzk51 = t1355 * tzk48;

  t1356 = t1348 * t1348;
  t1357 = t1349 * t1349;
  t1359 = t1356 / t1357;
  tzk52 = t1359 * tzk48;

  t1363 = t1356 * t1344 / t1357 / t1345;
  tzk53 = t1363 * tzk48;

  t1367 = t1356 * t1348 / t1357 / t1349;
  tzk54 = t1367 * tzk48;

  t1371 = t1356 * t1352 / t1357 / t1353;
  tzk55 = t1371 * tzk48;

  t1372 = t1356 * t1356;
  t1373 = t1357 * t1357;
  t1375 = t1372 / t1373;
  tzk56 = t1375 * tzk48;

  t1381 = t661 * t673;
  t1391 = t407 * t677 * t16 * t680 * t36 / 0.96e2 + 0.21437009059034868485e-3 * t1381 * t704 * t707 * t708 * t711 * t11 / t473 * t394;
  t1400 = log(0.1e1 + 0.65854491829355115987e0 * t1391 * t661 / (0.1e1 + 0.65854491829355115987e0 * t1381 * t1391));
  tzk57 = t651 * t659 * t1400;

  t1404 = t550 * t659 * t1400;
  tzk58 = t1347 * t650 * t1404;

  tzk59 = t1351 * t650 * t1404;

  tzk60 = t1355 * t650 * t1404;

  tzk61 = t1359 * t650 * t1404;

  tzk62 = t1363 * t650 * t1404;

  tzk63 = t1367 * t650 * t1404;

  tzk64 = t1371 * t650 * t1404;

  tzk65 = t1375 * t650 * t1404;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC)) {
    out->zk[ip*p->dim.zk + 0] += tzk0;
    out->zk[ip*p->dim.zk + 1] += tzk1;
    out->zk[ip*p->dim.zk + 2] += tzk2;
    out->zk[ip*p->dim.zk + 3] += tzk3;
    out->zk[ip*p->dim.zk + 4] += tzk4;
    out->zk[ip*p->dim.zk + 5] += tzk5;
    out->zk[ip*p->dim.zk + 6] += tzk6;
    out->zk[ip*p->dim.zk + 7] += tzk7;
    out->zk[ip*p->dim.zk + 8] += tzk8;
    out->zk[ip*p->dim.zk + 9] += tzk9;
    out->zk[ip*p->dim.zk + 10] += tzk10;
    out->zk[ip*p->dim.zk + 11] += tzk11;
    out->zk[ip*p->dim.zk + 12] += tzk12;
    out->zk[ip*p->dim.zk + 13] += tzk13;
    out->zk[ip*p->dim.zk + 14] += tzk14;
    out->zk[ip*p->dim.zk + 15] += tzk15;
    out->zk[ip*p->dim.zk + 16] += tzk16;
    out->zk[ip*p->dim.zk + 17] += tzk17;
    out->zk[ip*p->dim.zk + 18] += tzk18;
    out->zk[ip*p->dim.zk + 19] += tzk19;
    out->zk[ip*p->dim.zk + 20] += tzk20;
    out->zk[ip*p->dim.zk + 21] += tzk21;
    out->zk[ip*p->dim.zk + 22] += tzk22;
    out->zk[ip*p->dim.zk + 23] += tzk23;
    out->zk[ip*p->dim.zk + 24] += tzk24;
    out->zk[ip*p->dim.zk + 25] += tzk25;
    out->zk[ip*p->dim.zk + 26] += tzk26;
    out->zk[ip*p->dim.zk + 27] += tzk27;
    out->zk[ip*p->dim.zk + 28] += tzk28;
    out->zk[ip*p->dim.zk + 29] += tzk29;
    out->zk[ip*p->dim.zk + 30] += tzk30;
    out->zk[ip*p->dim.zk + 31] += tzk31;
    out->zk[ip*p->dim.zk + 32] += tzk32;
    out->zk[ip*p->dim.zk + 33] += tzk33;
    out->zk[ip*p->dim.zk + 34] += tzk34;
    out->zk[ip*p->dim.zk + 35] += tzk35;
    out->zk[ip*p->dim.zk + 36] += tzk36;
    out->zk[ip*p->dim.zk + 37] += tzk37;
    out->zk[ip*p->dim.zk + 38] += tzk38;
    out->zk[ip*p->dim.zk + 39] += tzk39;
    out->zk[ip*p->dim.zk + 40] += tzk40;
    out->zk[ip*p->dim.zk + 41] += tzk41;
    out->zk[ip*p->dim.zk + 42] += tzk42;
    out->zk[ip*p->dim.zk + 43] += tzk43;
    out->zk[ip*p->dim.zk + 44] += tzk44;
    out->zk[ip*p->dim.zk + 45] += tzk45;
    out->zk[ip*p->dim.zk + 46] += tzk46;
    out->zk[ip*p->dim.zk + 47] += tzk47;
    out->zk[ip*p->dim.zk + 48] += tzk48;
    out->zk[ip*p->dim.zk + 49] += tzk49;
    out->zk[ip*p->dim.zk + 50] += tzk50;
    out->zk[ip*p->dim.zk + 51] += tzk51;
    out->zk[ip*p->dim.zk + 52] += tzk52;
    out->zk[ip*p->dim.zk + 53] += tzk53;
    out->zk[ip*p->dim.zk + 54] += tzk54;
    out->zk[ip*p->dim.zk + 55] += tzk55;
    out->zk[ip*p->dim.zk + 56] += tzk56;
    out->zk[ip*p->dim.zk + 57] += tzk57;
    out->zk[ip*p->dim.zk + 58] += tzk58;
    out->zk[ip*p->dim.zk + 59] += tzk59;
    out->zk[ip*p->dim.zk + 60] += tzk60;
    out->zk[ip*p->dim.zk + 61] += tzk61;
    out->zk[ip*p->dim.zk + 62] += tzk62;
    out->zk[ip*p->dim.zk + 63] += tzk63;
    out->zk[ip*p->dim.zk + 64] += tzk64;
    out->zk[ip*p->dim.zk + 65] += tzk65;
  }

}

#endif

